### ISSUE TITLE
checking for V8 files in default path... not found

### ISSUE THREAD

**Issue by NickColley** [phpv8/v8js#125]
➜  /  ls /usr/lib64/libv8.so.3.14.5 
/usr/lib64/libv8.so.3.14.5
➜  /  sudo pecl install v8js-beta  
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/v8js.so' - /usr/lib64/php/modules/v8js.so: cannot open shared object file: No such file or directory in Unknown on line 0
downloading v8js-0.1.5.tgz ...
Starting to download v8js-0.1.5.tgz (37,829 bytes)
..........done: 37,829 bytes
13 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
Please provide the installation prefix of libv8 [autodetect] : /usr/lib64/
building in /var/tmp/pear-build-root3VjQbA/v8js-0.1.5
running: /var/tmp/v8js/configure --with-v8js=/usr/lib64/
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for V8 Javascript Engine... yes, shared
checking for V8 files in default path... not found
configure: error: Please reinstall the v8 distribution
ERROR: `/var/tmp/v8js/configure --with-v8js=/usr/lib64/' failed

**Comment by clowestab** [comment]
@stesie On Ubuntu 14.04 x64 I cannot install the latest version of libv8.

`fetch v8` and `gclient sync` result in:

```
Syncing projects:  93% (15/16) v8/buildtools/third_party/libc++/trunk WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/icu.git" "/tmp/v8/third_party/_gclient_icu_8eEHf0"' in /tmp failed; will retry after a short nap...
[0:01:50] Still working on:
[0:01:50]   v8/third_party/icu
```

Could you provide any insight on how one compiles the latest v8 as that outlined in the README does not work.

Many thanks

**Comment by stesie** [comment]
@clowestab please open a new issue, this one's closed for more then a year now

What happens if you run the mentioned command manually?

```
"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/icu.git" "/tmp/v8/third_party/_gclient_icu_8eEHf0"
```

no space left on disk? slow or broken internet connection?

**Comment by archae0pteryx** [comment]
I've been having the same issue on os x. Am I missing something obvious here? I installed v8 via homebrew and passed `./configure --with-v8js=/usr/local/Cellar/v8/7.4.288.25` and i've tried compiling v8 from source and passed the path there as well but still get the same error. The path it's expecting is the one that contains the d8 binary correct?
