### ISSUE TITLE
nodejs: undefined symbol: _ZN2v82V820SetFatalErrorHandlerEPFvPKcS2_E

### ISSUE THREAD

**Issue by datnq201088** [phpv8/v8js#169]
I have completed install `v8js` on Ubuntu. `V8js` works fine. But when I run `npm install` , I get this error : 

     /usr/bin/nodejs: symbol lookup error: /usr/bin/nodejs: undefined symbol: _ZN2v82V820SetFatalErrorHandlerEPFvPKcS2_E

**Comment by datnq201088** [comment]
I had change folder build v8 `/usr` to `/opt/v8`. It works fine!

**Comment by stesie** [comment]
yes, that's the way to go :-)
Sorry for not answering yesterday
