### ISSUE TITLE
Access public - Methods in child class

### ISSUE THREAD

**Issue by kinimodmeyer** [phpv8/v8js#183]
hello guys,
i created a child class to add more functionality to V8Js (dont know if this is right).

```php
class test extends V8Js
{
    public function hello()
    {
        die('hello world');
    }
}
```
now i want to access this method in my js code with 

```javascript
PHP.hello();
```

but i just get the following error:

`TypeError: undefined is not a function`

with properties it works like expected:

```php
class test extends V8Js
{
    public $hello = 'hello world';
}
```

```javascript
PHP.hello;
```

i hope you can help me with this.

**Comment by stesie** [comment]
TODOs for PHP 5.x

- [ ] implement method export in V8Js::__construct without any PHP magic functions
- [ ] test private & protected methods must not be exported
- [ ] neither may methods from the base object be available
- [ ] __sleep and __wakeup must not be overridable (PHP side) and never be exported

I consider `__get`, `__set`, `__call`, `__invoke` et al beyond the scope of this ticket, and actually tend to not implement them.  All that stuff already works with normal object export and probably will be pretty easy once #72 lands finally (in V8Js 2.0.0 or so).
