### ISSUE TITLE
checking for V8 files in default path... not found

### ISSUE THREAD

**Issue by dotMastaz** [phpv8/v8js#206]
Hello,

I copy the libv8.so to /usr/ib/ , /usr/local/lib/ , /opt/v8/lib/ , /usr/local/v8/lib/

And after ' sudo pecl install v8js' : 

I have this :+1: 
checking for V8 Javascript Engine... yes, shared
checking for V8 files in default path... not found
configure: error: Please reinstall the v8 distribution

Thanks for your help !

**Comment by stesie** [comment]
Hi,

you don't just have to copy over the `libv8.so` file, but at least also the `libv8_libplatform.a` as well as the include header files.  See https://github.com/phpv8/v8js/blob/php7/README.Linux.md

If  you let V8 build its own version of libicu, than that one as well (possibly including the rpath fix, see README)

Hope that helps :-)

**Comment by dotMastaz** [comment]
Hello,

Compil v8js OK !!
Very big thank you very much !!
