### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by fterragna** [phpv8/v8js#215]
Hey,

I'm hitting into an error while running ./configure CXXFLAGS="-Wno-c++11-narrowing"

```
checking for natives_blob.bin... not found
configure: error: Please provide V8 native blob as needed
```

Any ideas?

**Comment by stesie** [comment]
Did you compile your V8 with external snapshot support?  If so, then it should have created `natives_blob.bin` file and V8Js can't find that file.

Otherwise it might be a general compilation error. Please see `config.log` file. Please provide that one here.

**Comment by fterragna** [comment]
See https://github.com/phpv8/v8js/issues/216
