### ISSUE TITLE
Cannot install on php 7.0.4 (ubuntu 16.04)

### ISSUE THREAD

**Issue by alextartan** [phpv8/v8js#227]
I'm trying to run `sudo pecl install v8js-1.2.0`

The initial output is:
`Configuring for:`
`PHP Api Version:             20151012`
`Zend Module Api No:       20151012`
`Zend Extension Api No:   320151012`

I'm getting (last error):
`Makefile:218: recipe for target 'v8js_class.lo' failed`
`make: *** [v8js_class.lo] Error 1`
`ERROR: `make' failed`

To avoid spamming this page, I've made a pastebin with the entire output: http://pastebin.com/jjAi3k9j

Any help is greatly appreciated!

UPDATE:
I did however manage to install version 1.0.0 with `sudo pecl install v8js-1.0.0`

**Comment by pinepain** [comment]
For further readers:

I added PPA for v8 5.2 series - https://launchpad.net/~pinepain/+archive/ubuntu/libv8-5.2, other changes:
 - add 16.04 xenial build;
 - remove 15.04 vivid build.

Hope, you will find it useful.

I didn't test v8js with it but it should be compatible.

**Comment by stesie** [comment]
Nice catch, this possibly broke with most recent c++ headers, where `#include <cmath>` now undefines the `isnan` macro which is required by `php.h`.

The old v8js version works as it includes headers in a different order (which however breaks the build on windows)

#229 has a work-around, I'll merge it after verifying it builds correctly (including Windows).  Will take me a while so
