### ISSUE TITLE
Anyone had luck compiling for 32bit linux?

### ISSUE THREAD

**Issue by cdomigan** [phpv8/v8js#232]
Been banging my head against this for a few days now. Am on Ubuntu 14.04. Can compile V8 fine - shell runs etc. But `make test` on v8js leads to all tests failing. Testing on PHP CLI gives `undefined symbol: _ZN2v84base5MutexC1Ev`

Have tried all suggestions on here, and have scoured the net.

Anyone had luck compiling this successfully for 32bit? It's driving me crazy!

**Comment by stesie** [comment]
I'm afraid but nope, never tried it off amd64 (and Windows after all) and I don't remember anyone who tried or complained :)

Does you `libv8.so` have the symbol defined?

$ nm libv8.so  | grep  _ZN2v84base5MutexC1Ev
0000000000a4e880 T _ZN2v84base5MutexC1Ev

... on amd64 it has, (letter "T" for text section) ... if it hasn't it probably shows a capital "U" for undefined

You might want to continue checking "libv8_libbase.a" file for it.  If it has it just try linking with it included. The dirty way: modify `Makefile` after `configure` (which you already ran) and seek for "libv8_libplatform.a", just add the full path to "libv8_libbase.a" as well, then `make clean`, `make` ...

**Comment by cdomigan** [comment]
Thanks @stesie - I've given up and moved my stack over to 64bit (long overdue anyway!)
