### ISSUE TITLE
502 Bad Gateway (Segmentation fault when using array_walk_recursive)

### ISSUE THREAD

**Issue by several27** [phpv8/v8js#246]
Hi,
I'm getting 502 Bad Gateway with the following error in error.log
`2016/07/13 14:53:24 [error] 769#769: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream`

This is the code that I'm trying to execute:
```
Route::get('v8js', function () {
    $data = SomeLaravelModel::find(10)->first()->toArray();

    $v8            = new V8Js();
    $v8->some_data = $data;
    $v8->executeString('print(JSON.stringify(PHP));');
});
```

I have installed v8 version 5.1.99 (as the newest is not compiling properly) with the newest version of homestead and laravel. I'm using php7 and also v8js from php7 branch.

Most of the time it works perfectly fine, but for some unknown reason the code above is not working.

What's even more interesting: if I replace the line where I assign `$data` to `some_data` with:
```
    $v8->questionnairee = \unserialize(\serialize($data));
```
it works as expected.

**Edit**:
Relevant log line from the syslog:
```
Jul 18 10:27:42 homestead kernel: [ 9676.279356] php-fpm7.0[4581]: segfault at 0 ip 00007f07ecff8b13 sp 00007ffdf2fbcc50 error 4 in libv8.so[7f07ec955000+bb5000]
```

**Edit 2**: 
Apparently its a more generic issue not related to laravel.
The code below is responsible for segmentation fault above:
```
$v8 = new V8Js();
$array = ['lorem' => 'ipsum'];
array_walk_recursive($array, function (&$item) {});
$v8->some_array = $array;
```

**Comment by tahpot** [comment]
I can confirm your edit 2 snippet also segfaults for me.

@stesie Any thoughts on this? This is rendering v8js unusable.

**Comment by stesie** [comment]
@several27 could you please confirm that #252 also fixes the issue you've got with Laravel? I don't have Laravel around (and unfortunately haven't had time to use it so far), so it would be cool if you could test that.

**Comment by several27** [comment]
@stesie As I mentioned in the **Edit 2** the issue is not related to Laravel like I initially thought. However, just now I was trying to install v8js and all of the tests are failing for some reason

```
Number of tests :  160               158
Tests skipped   :    2 (  1.2%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :  158 ( 98.8%) (100.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    0 (  0.0%) (  0.0%)
```

I'm using older version of v8: 5.1.99, so that might the reason, however due to https://github.com/phpv8/v8js/issues/238 I'm not able to install the latest one.

**Comment by stesie** [comment]
@several27 5.1.99 should generally work fine ... have you looked into the `tests/*.out` files, what do those tell?

Any yes, I got that you derived the code in "Edit 2" from that, but I wasn't 100% sure if my fix really fixes the initial issue or not. The problem is related to reference variables, but the first code snippet doesn't show it uses references (so Laravel might very well use some internally) ...

... so it was just to make sure as I've tested only against the code from "Edit 2" (and it fixes that)

**Comment by several27** [comment]
@stesie Thank you so much for fixing the problem! 

Also, apparently I had xdebug enabled and it was looking for a modules/xdebug.so file. It passed all tests after disabling xdebug.

Thanks!
