### ISSUE TITLE
not support v8 5.4.374

### ISSUE THREAD

**Issue by imbubble** [phpv8/v8js#251]
what is the max version supported?

got error in v8 5.4.374:

```
configure: error: could not determine libv8 version
ERROR: `/tmp/pear/temp/v8js/configure --with-php-config=/usr/bin/php-config --with-v8js' failed
```

**Comment by stesie** [comment]
@imbubble I can confirm version 5.4.3 working, but I'll look into supporting the most recent ones also, of course :)

**Comment by stesie** [comment]
I've now compiled V8 5.4.374 myself and can confirm it working with latest version of V8Js (1.3.1 or just php7 branch from Git)

**Comment by stesie** [comment]
... therefore please provide your `config.log` file somewhere, it should have some more detailed info on what's going wrong

**Comment by imbubble** [comment]
Thanks for reply.

here is `config.log` and `v8.files` installed:

[v8.files.txt](https://github.com/phpv8/v8js/files/414448/v8.files.txt)

[config.log.txt](https://github.com/phpv8/v8js/files/414449/config.log.txt)

on `ArchLinux`, `PHP 7.0.9`

**Comment by AlexMasterov** [comment]
@imbubble

In the list of files V8 does not have the required libraries.
It was probably built without `library=shared` flag or they just were not copied.

**Comment by imbubble** [comment]
@AlexMasterov 

okay, seems that's the point. thanks.
