### ISSUE TITLE
win64 support?

### ISSUE THREAD

**Issue by kaysond** [phpv8/v8js#263]
Do you have win64 binaries? Is there anything that would prevent me from compiling an extension for 64bit php? Figure I'd ask before I try it

**Comment by stesie** [comment]
I don't have any.  I haven't done anything with Windows for quite a while -- apart from once getting this project to compile and configuring AppVeyor ... but I got nothing that isn't publicly visible from here.

And to be honest, I don't know about 64bit extension, never tried. But I don't know why it shouldn't work

**Comment by AlexMasterov** [comment]
@kaysond see #210

**Comment by kaysond** [comment]
Thanks @AlexMasterov 
@stesie guess it does work. Might wanna add something to the win32 readme?
Found 64 bit dlls here:
https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by stesie** [comment]
Sure we can add a reference to there.
Would you like to come up with a pull request?
