### ISSUE TITLE
Heroku - failed to compile

### ISSUE THREAD

**Issue by several27** [phpv8/v8js#265]
Hi,
I have a problem when trying to deploy heroku app.
I'm getting the `push failed` error and this is the exact log pointing to the problem with a v8js version (?).

```
-----> PHP app detected
-----> Bootstrapping...
-----> Installing platform packages...
       - php (7.0.11)
       - ext-mbstring (bundled with php)
       - ext-v8js (1.3.1)
       - apache (2.4.20)
       - nginx (1.8.1)
-----> Installing dependencies...
       Composer version 1.2.1 2016-09-12 11:27:19
       Loading composer repositories with package information
       Installing dependencies from lock file
       Your requirements could not be resolved to an installable set of packages.

         Problem 1
           - The requested PHP extension ext-v8js 1.3.1 has the wrong version (1.2.0) installed. Install or enable PHP's v8js extension.

 !     Push rejected, failed to compile PHP app.
 !     Push failed
```

**Comment by pinepain** [comment]
Log says for itself:

>           - The requested PHP extension ext-v8js 1.3.1 has the wrong version (1.2.0) installed. Install or enable PHP's v8js extension.

Your app requires version 1.3.1 but 1.2.0 installed.

**Comment by several27** [comment]
@pinepain But it's an heroku app, with linked build pack through `HEROKU_PHP_PLATFORM_REPOSITORIES`. Shouldn't it be automatically updated to the latest?

**Comment by pinepain** [comment]
`WARNING: Your 'composer.lock' is not up to date with` and then `Installing dependencies from lock file`: you have your .lock file out of sync with composer.json, try to sync it (run `composer update`) and then publish app again.

**Comment by several27** [comment]
My bad, was playing around too much. The problem still persists. In my opinion something is wrong with the [packages.json](https://heroku-v8js.s3.amazonaws.com/dist-cedar-14-stable/packages.json), it seems like it uses older version for some reason.

**Comment by pinepain** [comment]
Hm, then you'd better wait for @stesie, I haven't looked into v8js heroku since may or so.

**Comment by stesie** [comment]
@several27 the point is that I haven't yet compiled v8js for Heroku since 1.2.0

But thanks for pointing that out, I really should get some automatism installed :)

**Comment by several27** [comment]
@stesie I thought so. If you could please update it that'd be great.

Thanks

**Comment by stesie** [comment]
Sorry, I forgot about rebuilding the packages. Now it's done.
