### ISSUE TITLE
Compiling Error on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by peterrobie** [phpv8/v8js#271]
Looking for any suggestions for a resolution on this. This is the end result of the following command:
**make native library=shared snapshot=on -j8**

....
  CXX(target) /tmp/v8/out/native/obj.target/cctest/test/cctest/expression-type-collector.o
  CXX(target) /tmp/v8/out/native/obj.target/cctest/test/cctest/interpreter/test-bytecode-generator.o
  CXX(target) /tmp/v8/out/native/obj.target/cctest/test/cctest/interpreter/test-interpreter.o
  CXX(target) /tmp/v8/out/native/obj.target/cctest/test/cctest/gay-fixed.o
  CXX(target) /tmp/v8/out/native/obj.target/cctest/test/cctest/gay-precision.o
  CXX(target) /tmp/v8/out/native/obj.target/cctest/test/cctest/gay-shortest.o
  CXX(target) /tmp/v8/out/native/obj.target/cctest/test/cctest/heap/test-alloc.o
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (trunk 255169)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /tmp/v8/third_party/llvm-build/Release+Asserts/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/gay-fixed-ebe3cc.cpp
clang: note: diagnostic msg: /tmp/gay-fixed-ebe3cc.sh
clang: note: diagnostic msg:

********************
test/cctest/cctest.target.native.mk:327: recipe for target '/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-fixed.o' failed
make[1]: *** [/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-fixed.o] Error 254
make[1]: *** Waiting for unfinished jobs....
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (trunk 255169)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /tmp/v8/third_party/llvm-build/Release+Asserts/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/gay-precision-971fac.cpp
clang: note: diagnostic msg: /tmp/gay-precision-971fac.sh
clang: note: diagnostic msg:

********************
test/cctest/cctest.target.native.mk:327: recipe for target '/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-precision.o' failed
make[1]: *** [/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-precision.o] Error 254
make[1]: Leaving directory '/tmp/v8/out'
Makefile:312: recipe for target 'native' failed
make: *** [native] Error 2

**Comment by stesie** [comment]
Try without the `-j8` option to make, or maybe reduce to `-j4` or `-j2`. It's the number of compiler processes ran in parallel ... and I suppose your system is running out of RAM.

You also might want to check `dmesg` for kernel log messages on why its killing the process. But I'd guess it's the "out of memory" handler

**Comment by peterrobie** [comment]
Thanks stesie. I'm running the build again with -j2 to be on the safe side and I'll post the results of the build here.

**Comment by peterrobie** [comment]
All is working. Thanks for the tip. Could the Readme be updated to reflect this for others trying to compile?

**Comment by stesie** [comment]
You're welcome. I've just added notices to the README file, thanks for pointing that out.
