### ISSUE TITLE
Mac os brew - No available formula, "php56-v8js" 

### ISSUE THREAD

**Issue by magichim** [phpv8/v8js#274]
When I install php56-v8js by using brew, I got the message that 'No available formula with the name "php56-v8js" '

My OS is Sierra 10.12.1 and php version is 5.6.25.

what should do I do in this case???

**Comment by stesie** [comment]
I think this is a problem with homebrew itself. I'm not on a Mac but I'd recommend to ask there, or to contact the maintainer of the v8js formula for homebrew

**Comment by pinepain** [comment]
@magichim there is v8js formula for PHP5.6 in homebrew-php - https://github.com/Homebrew/homebrew-php/blob/master/Formula/php56-v8js.rb. Please, make sure you have homebrew/php tapped (with it dependencies) and it is up to date.
