### ISSUE TITLE
libv8_libplatform not found - Highlight strongly to use "/tmp" folder to compile V8

### ISSUE THREAD

**Issue by gabeljz** [phpv8/v8js#281]
In v8js/README.Linux.md, the command `cd /tmp` entered the "**\tmp**" folder for the rest of the steps to execute.

But for my own housekeeping, I changed it to another folder, "/tmp/google-V8".

At the `./configure --with-v8js=/opt/v8` step, an error is thrown saying that the "**libv8_libplatform**" is not found.

After several hours of googling and trying many solutions for other unrelated problems with the same sympton, I retry the whole instruction in v8js/README.Linux.md down to the letters.

The working directory must remain as "**\tmp**" folder, then the whole compilation and installation will run smoothly.

Suggested todo: Highlight strongly at the instruction to use "**/tmp**" folder. Or, implement a more robust mechanism to detect the custom compiled v8 engine.

**Comment by stesie** [comment]
I don't think that that is the case. Actually I almost never build in /tmp myself.
Do you have some console log around where we could find out from what's gone wrong otherwise?

**Comment by gabeljz** [comment]
I just tried to reinstalled everything, this time using "**/tmp**", but it can not find the "** libv8_libplatform**" library again.

This is the bash script that I run to compile and install everything as per v8js/README.Linux.md, please rename it to "compile_V8.sh". I run it with `$ sudo bash /path/to/compile_V8.sh`

[compile_V8_sh.txt](https://github.com/phpv8/v8js/files/683711/compile_V8_sh.txt)

This is the log that I get from running the bash script above.

[compile_V8_log.txt](https://github.com/phpv8/v8js/files/683719/compile_V8_log.txt)

A thought just occurred to me, is this problem caused by running the script with "**sudo**"?

**Comment by gabeljz** [comment]
I have kinda narrowed down the cause of the problem to this:

1. Running `ninja -C out.gn/x64.release/` in a bash script. Compilation will complete successfully.
2. Copying the compiled file `sudo cp out.gn/x64.release/lib*.so out.gn/x64.release/*_blob.bin /opt/v8/lib/`
3. Received error message: `cp: cannot stat ‘out.gn/x64.release/lib*.so’: No such file or directory`

**Comment by gabeljz** [comment]
@stesie I still can not overcome this issue.

On my local machine, core i7 quad-core, 16GB ram, I can compile by running the commands one-by-one.

Following exactly the same procedure on an Amazon t2.micro, I will encounter back the same error.

Now, I am suspecting that the `ninja -C out.gn/x64.release/` simply failed to compile fully due to limited system resources.

I still do not have a good idea of the problem, definitely no solution.

I recommend to close this issue as "Wont fix".
