### ISSUE TITLE
fetch v8 error

### ISSUE THREAD

**Issue by qiaoyiyang** [phpv8/v8js#283]
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /tmp
Traceback (most recent call last):
  File "/tmp/depot_tools/fetch.py", line 300, in <module>
    sys.exit(main())
  File "/tmp/depot_tools/fetch.py", line 295, in main
    return run(options, spec, root)
  File "/tmp/depot_tools/fetch.py", line 289, in run
    return checkout.init()
  File "/tmp/depot_tools/fetch.py", line 132, in init
    self.run_gclient(*sync_cmd)
  File "/tmp/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/tmp/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2

Please help me,thank you.

**Comment by stesie** [comment]
Could you please try running the failing command manually. Be careful with the asterisk so that your shell doesn't glob it

```
download_from_google_storage --no_resume --platform="linux*" --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1
```

... I suppose it's some SSL error with Python :-)

**Comment by qiaoyiyang** [comment]
Ah,so..
`
download_from_google_storage: command not found`

**Comment by stesie** [comment]
it's part of the `depot_tools` that need to be part of the `PATH`

**Comment by qiaoyiyang** [comment]
I'm sorry to take up your time...
Now shows：

> Traceback (most recent call last):
  File "/tmp/depot_tools/download_from_google_storage.py", line 538, in <module>
    sys.exit(main(sys.argv))
  File "/tmp/depot_tools/download_from_google_storage.py", line 534, in main
    options.extract)
  File "/tmp/depot_tools/download_from_google_storage.py", line 358, in download_from_google_storage
    ignore_errors, output, sha1_file, auto_platform)
  File "/tmp/depot_tools/download_from_google_storage.py", line 152, in enumerate_work_queue
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: v8/buildtools/linux64/clang-format.sha1 not found.

**Comment by stesie** [comment]
Are you in the correct directory?  I.e. the one that has the `v8` folder underneath?

**Comment by qiaoyiyang** [comment]
Yes, I am in the README. Linux. Md to install.But the execution to `fetch v8` need more than an hour
I perform in the `/tmp` directory `export PATH = ` pwd ` / depot_tools: "$PATH"`, you can run the instructions just now.

**Comment by qiaoyiyang** [comment]
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )

**Comment by qiaoyiyang** [comment]
Thank you.
I am successful installation in the following way：

```
sudo apt-get install libv8-dev g++ cpp

sudo apt install php-pear

sudo apt install php7.0-dev

wget http://ppa.launchpad.net/pinepain/libv8-5.2/ubuntu/pool/main/libv/libv8-5.2/libv8-5.2-d8_5.2.371-ppa1~xenial_amd64.deb
wget http://ppa.launchpad.net/pinepain/libv8-5.2/ubuntu/pool/main/libv/libv8-5.2/libv8-5.2-dbg_5.2.371-ppa1~xenial_amd64.deb
wget http://ppa.launchpad.net/pinepain/libv8-5.2/ubuntu/pool/main/libv/libv8-5.2/libv8-5.2-dev_5.2.371-ppa1~xenial_amd64.deb
wget http://ppa.launchpad.net/pinepain/libv8-5.2/ubuntu/pool/main/libv/libv8-5.2/libv8-5.2.371_5.2.371-ppa1~xenial_amd64.deb

sudo dpkg -i libv8-5.2.371_5.2.371-ppa1~xenial_amd64.deb
sudo dpkg -i libv8-5.2-d8_5.2.371-ppa1~xenial_amd64.deb
sudo dpkg -i libv8-5.2-dbg_5.2.371-ppa1~xenial_amd64.deb
sudo dpkg -i libv8-5.2-dev_5.2.371-ppa1~xenial_amd64.deb

sudo pecl install v8js-1.3.3
```

**Comment by yusupprog** [comment]
<img width="965" alt="screen shot 2018-02-26 at 14 27 28" src="https://user-images.githubusercontent.com/11705239/36660144-419cca4c-1b01-11e8-8c60-de4f90812706.png">

Same error as @qiaoyiyang 

I'm on Operating System: CentOS Linux 7 (Core)
