### ISSUE TITLE
Compile on FreeBSD

### ISSUE THREAD

**Issue by sebbio** [phpv8/v8js#288]
> checking for gawk... no
> checking for nawk... nawk
> checking if nawk is broken... no
> checking for V8 Javascript Engine... yes, shared
> checking for V8 files in default path... found in /usr/local
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking how to run the C++ preprocessor... g++ -E
> checking for C standard version... c++11
> checking how to allow c++11 narrowing...
> checking for libv8_libplatform... checking for libv8_libplatform... configure: error: could not find libv8_libplatform library

but file libv8_libplatform.a exist in /usr/local/lib

**Comment by sebbio** [comment]
v8 version 5.1.281.47

**Comment by stesie** [comment]
please provide the `config.log` file, it should have some more details on what actually went wrong

**Comment by sebbio** [comment]
> This file contains any messages produced by compilers while
> running configure, to aid debugging if configure makes a mistake.
> 
> It was created by configure, which was
> generated by GNU Autoconf 2.69.  Invocation command line was
> 
>   $ ./configure 
> 
> ## --------- ##
> ## Platform. ##
> ## --------- ##
> 
> hostname = ns1.webzvit.com.ua
> uname -m = amd64
> uname -r = 11.0-RELEASE-p2
> uname -s = FreeBSD
> uname -v = FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC 
> 
> /usr/bin/uname -p = amd64
> /bin/uname -X     = unknown
> 
> /bin/arch              = unknown
> /usr/bin/arch -k       = unknown
> /usr/convex/getsysinfo = unknown
> /usr/bin/hostinfo      = unknown
> /bin/machine           = unknown
> /usr/bin/oslevel       = unknown
> /bin/universe          = unknown
> 
> PATH: /sbin
> PATH: /bin
> PATH: /usr/sbin
> PATH: /usr/bin
> PATH: /usr/local/sbin
> PATH: /usr/local/bin
> PATH: /root/bin
> 
> 
> ## ----------- ##
> ## Core tests. ##
> ## ----------- ##
> 
> configure:2468: checking for grep that handles long lines and -e
> configure:2526: result: /usr/bin/grep
> configure:2531: checking for egrep
> configure:2593: result: /usr/bin/grep -E
> configure:2598: checking for a sed that does not truncate output
> configure:2652: result: /usr/bin/sed
> configure:2789: checking for cc
> configure:2805: found /usr/bin/cc
> configure:2816: result: cc
> configure:2847: checking for C compiler version
> configure:2856: cc --version >&5
> FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
> Target: x86_64-unknown-freebsd11.0
> Thread model: posix
> InstalledDir: /usr/bin
> configure:2867: $? = 0
> configure:2856: cc -v >&5
> FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
> Target: x86_64-unknown-freebsd11.0
> Thread model: posix
> InstalledDir: /usr/bin
> configure:2867: $? = 0
> configure:2856: cc -V >&5
> cc: error: argument to '-V' is missing (expected 1 value)
> cc: error: no input files
> configure:2867: $? = 1
> configure:2856: cc -qversion >&5
> cc: error: unknown argument: '-qversion'
> cc: error: no input files
> configure:2867: $? = 1
> configure:2887: checking whether the C compiler works
> configure:2909: cc    conftest.c  >&5
> configure:2913: $? = 0
> configure:2961: result: yes
> configure:2964: checking for C compiler default output file name
> configure:2966: result: a.out
> configure:2972: checking for suffix of executables
> configure:2979: cc -o conftest    conftest.c  >&5
> configure:2983: $? = 0
> configure:3005: result: 
> configure:3027: checking whether we are cross compiling
> configure:3035: cc -o conftest    conftest.c  >&5
> configure:3039: $? = 0
> configure:3046: ./conftest
> configure:3050: $? = 0
> configure:3065: result: no
> configure:3070: checking for suffix of object files
> configure:3092: cc -c   conftest.c >&5
> configure:3096: $? = 0
> configure:3117: result: o
> configure:3121: checking whether we are using the GNU C compiler
> configure:3140: cc -c   conftest.c >&5
> configure:3140: $? = 0
> configure:3149: result: yes
> configure:3158: checking whether cc accepts -g
> configure:3178: cc -c -g  conftest.c >&5
> configure:3178: $? = 0
> configure:3219: result: yes
> configure:3236: checking for cc option to accept ISO C89
> configure:3299: cc  -c -g -O2  conftest.c >&5
> configure:3299: $? = 0
> configure:3312: result: none needed
> configure:3338: checking how to run the C preprocessor
> configure:3369: cc -E  conftest.c
> configure:3369: $? = 0
> configure:3383: cc -E  conftest.c
> conftest.c:9:10: fatal error: 'ac_nonexistent.h' file not found
> #include <ac_nonexistent.h>
>          ^
> 1 error generated.
> configure:3383: $? = 1
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> | #include <ac_nonexistent.h>
> configure:3408: result: cc -E
> configure:3428: cc -E  conftest.c
> configure:3428: $? = 0
> configure:3442: cc -E  conftest.c
> conftest.c:9:10: fatal error: 'ac_nonexistent.h' file not found
> #include <ac_nonexistent.h>
>          ^
> 1 error generated.
> configure:3442: $? = 1
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> | #include <ac_nonexistent.h>
> configure:3473: checking for icc
> configure:3482: result: no
> configure:3496: checking for suncc
> configure:3505: result: no
> configure:3523: checking whether cc understands -c and -o together
> configure:3551: cc -c conftest.c -o conftest2.o >&5
> configure:3555: $? = 0
> configure:3561: cc -c conftest.c -o conftest2.o >&5
> configure:3565: $? = 0
> configure:3620: result: yes
> configure:3634: checking for system library directory
> configure:3649: result: lib
> configure:3656: checking if compiler supports -R
> configure:3675: cc -o conftest -g -O2   conftest.c -R /usr/lib  >&5
> warning: unknown remark option '-R' [-Wunknown-warning-option]
> 1 warning generated.
> /usr/lib: file not recognized: File format not recognized
> cc: error: linker command failed with exit code 1 (use -v to see invocation)
> configure:3675: $? = 1
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> | 
> | int
> | main ()
> | {
> | 
> |   ;
> |   return 0;
> | }
> configure:3685: result: no
> configure:3690: checking if compiler supports -Wl,-rpath,
> configure:3709: cc -o conftest -g -O2   conftest.c -Wl,-rpath,/usr/lib  >&5
> configure:3709: $? = 0
> configure:3719: result: yes
> configure:3764: checking build system type
> configure:3778: result: amd64-unknown-freebsd11.0
> configure:3798: checking host system type
> configure:3811: result: amd64-unknown-freebsd11.0
> configure:3831: checking target system type
> configure:3844: result: amd64-unknown-freebsd11.0
> configure:3947: checking for PHP prefix
> configure:3949: result: /usr/local
> configure:3951: checking for PHP includes
> configure:3953: result: -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
> configure:3955: checking for PHP extension directory
> configure:3957: result: /usr/local/lib/php/20160303
> configure:3959: checking for PHP installed headers prefix
> configure:3961: result: /usr/local/include/php
> configure:3964: checking if debug is enabled
> configure:3990: result: no
> configure:3993: checking if zts is enabled
> configure:4019: result: no
> configure:4090: checking for re2c
> configure:4106: found /usr/local/bin/re2c
> configure:4117: result: re2c
> configure:4126: checking for re2c version
> configure:4140: result: 0.14.3 (ok)
> configure:4159: checking for gawk
> configure:4190: result: no
> configure:4159: checking for nawk
> configure:4176: found /usr/bin/nawk
> configure:4187: result: nawk
> configure:4210: checking if nawk is broken
> configure:4217: result: no
> configure:4230: checking for V8 Javascript Engine
> configure:4270: result: yes, shared
> configure:4291: checking for V8 files in default path
> configure:4296: result: found in /usr/local
> configure:4499: checking for g++
> configure:4515: found /usr/local/bin/g++
> configure:4526: result: g++
> configure:4553: checking for C++ compiler version
> configure:4562: g++ --version >&5
> g++ (FreeBSD Ports Collection) 4.9.4
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> configure:4573: $? = 0
> configure:4562: g++ -v >&5
> Using built-in specs.
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc49/gcc/x86_64-portbld-freebsd11.0/4.9.4/lto-wrapper
> Target: x86_64-portbld-freebsd11.0
> Configured with: /wrkdirs/usr/ports/lang/gcc/work/gcc-4.9.4/configure --disable-bootstrap --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc49 --libexecdir=/usr/local/libexec/gcc49 --program-suffix=49 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc49/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --with-ecj-jar=/usr/local/share/java/ecj-4.5.jar --enable-languages=c,c++,objc,fortran,java --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc49 --build=x86_64-portbld-freebsd11.0
> Thread model: posix
> gcc version 4.9.4 (FreeBSD Ports Collection) 
> configure:4573: $? = 0
> configure:4562: g++ -V >&5
> g++: error: unrecognized command line option '-V'
> g++: fatal error: no input files
> compilation terminated.
> configure:4573: $? = 1
> configure:4562: g++ -qversion >&5
> g++: error: unrecognized command line option '-qversion'
> g++: fatal error: no input files
> compilation terminated.
> configure:4573: $? = 1
> configure:4577: checking whether we are using the GNU C++ compiler
> configure:4596: g++ -c   conftest.cpp >&5
> configure:4596: $? = 0
> configure:4605: result: yes
> configure:4614: checking whether g++ accepts -g
> configure:4634: g++ -c -g  conftest.cpp >&5
> configure:4634: $? = 0
> configure:4675: result: yes
> configure:4703: checking how to run the C++ preprocessor
> configure:4730: g++ -E  conftest.cpp
> configure:4730: $? = 0
> configure:4744: g++ -E  conftest.cpp
> conftest.cpp:9:28: fatal error: ac_nonexistent.h: No such file or directory
>  #include <ac_nonexistent.h>
>                             ^
> compilation terminated.
> configure:4744: $? = 1
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> | #include <ac_nonexistent.h>
> configure:4769: result: g++ -E
> configure:4789: g++ -E  conftest.cpp
> configure:4789: $? = 0
> configure:4803: g++ -E  conftest.cpp
> conftest.cpp:9:28: fatal error: ac_nonexistent.h: No such file or directory
>  #include <ac_nonexistent.h>
>                             ^
> compilation terminated.
> configure:4803: $? = 1
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> | #include <ac_nonexistent.h>
> configure:4847: checking for C standard version
> configure:4872: g++ -o conftest -g -O2 -std=c++11  conftest.cpp -lstdc++  >&5
> configure:4872: $? = 0
> configure:4872: ./conftest
> configure:4872: $? = 0
> configure:4890: result: c++11
> configure:4893: checking how to allow c++11 narrowing
> configure:4922: g++ -o conftest -std=c++11   conftest.cpp -lstdc++  >&5
> conftest.cpp: In function 'int main()':
> conftest.cpp:10:45: warning: narrowing conversion of '-1' from 'int' to 'unsigned int' inside { } [-Wnarrowing]
>          struct { unsigned int x; } foo = {-1};
>                                              ^
> configure:4922: $? = 0
> configure:4922: ./conftest
> configure:4922: $? = 0
> configure:4992: result: 
> configure:5014: checking for libv8_libplatform
> configure:5035: g++ -o conftest -g -O2  -I/usr/local/include -std=c++11  -L/usr/local/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 >&5
> /usr/local/bin/ld: /usr/local/lib/libv8_libplatform.a(default-platfor): undefined reference to symbol '_ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv'
> //usr/lib/libc++.so.1: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> configure:5035: $? = 1
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> | 
> | 	  namespace v8 {
> | 		namespace platform {
> | 		  void* CreateDefaultPlatform(int thread_pool_size = 0);
> | 		}
> | 	  }
> | 
> | int
> | main ()
> | {
> |  v8::platform::CreateDefaultPlatform();
> |   ;
> |   return 0;
> | }
> configure:5045: checking for libv8_libplatform
> configure:5066: g++ -o conftest -g -O2  -I/usr/local/include -std=c++11  -L/usr/local/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 -lv8_libbase -lv8_libplatform -lv8 >&5
> /usr/local/bin/ld: /usr/local/lib/libv8_libplatform.a(default-platfor): undefined reference to symbol '_ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv'
> //usr/lib/libc++.so.1: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> configure:5066: $? = 1
> configure: failed program was:
> | /* confdefs.h */
> | #define PACKAGE_NAME ""
> | #define PACKAGE_TARNAME ""
> | #define PACKAGE_VERSION ""
> | #define PACKAGE_STRING ""
> | #define PACKAGE_BUGREPORT ""
> | #define PACKAGE_URL ""
> | /* end confdefs.h.  */
> | 
> | 	  namespace v8 {
> | 		namespace platform {
> | 		  void* CreateDefaultPlatform(int thread_pool_size = 0);
> | 		}
> | 	  }
> | 
> | int
> | main ()
> | {
> |  v8::platform::CreateDefaultPlatform();
> |   ;
> |   return 0;
> | }
> configure:5074: error: could not find libv8_libplatform library
> 
> ## ---------------- ##
> ## Cache variables. ##
> ## ---------------- ##
> 
> ac_cv_build=amd64-unknown-freebsd11.0
> ac_cv_c_compiler_gnu=yes
> ac_cv_cxx_compiler_gnu=yes
> ac_cv_env_CCC_set=''
> ac_cv_env_CCC_value=''
> ac_cv_env_CC_set=''
> ac_cv_env_CC_value=''
> ac_cv_env_CFLAGS_set=''
> ac_cv_env_CFLAGS_value=''
> ac_cv_env_CPPFLAGS_set=''
> ac_cv_env_CPPFLAGS_value=''
> ac_cv_env_CPP_set=''
> ac_cv_env_CPP_value=''
> ac_cv_env_CXXCPP_set=''
> ac_cv_env_CXXCPP_value=''
> ac_cv_env_CXXFLAGS_set=''
> ac_cv_env_CXXFLAGS_value=''
> ac_cv_env_CXX_set=''
> ac_cv_env_CXX_value=''
> ac_cv_env_LDFLAGS_set=''
> ac_cv_env_LDFLAGS_value=''
> ac_cv_env_LIBS_set=''
> ac_cv_env_LIBS_value=''
> ac_cv_env_build_alias_set=''
> ac_cv_env_build_alias_value=''
> ac_cv_env_host_alias_set=''
> ac_cv_env_host_alias_value=''
> ac_cv_env_target_alias_set=''
> ac_cv_env_target_alias_value=''
> ac_cv_host=amd64-unknown-freebsd11.0
> ac_cv_objext=o
> ac_cv_path_EGREP='/usr/bin/grep -E'
> ac_cv_path_GREP=/usr/bin/grep
> ac_cv_prog_AWK=nawk
> ac_cv_prog_CPP='cc -E'
> ac_cv_prog_CXXCPP='g++ -E'
> ac_cv_prog_RE2C=re2c
> ac_cv_prog_ac_ct_CC=cc
> ac_cv_prog_ac_ct_CXX=g++
> ac_cv_prog_cc_c89=''
> ac_cv_prog_cc_cc_c_o=yes
> ac_cv_prog_cc_g=yes
> ac_cv_prog_cxx_g=yes
> ac_cv_target=amd64-unknown-freebsd11.0
> ac_cv_v8_cstd=c++11
> ac_cv_v8_narrowing=''
> lt_cv_path_SED=/usr/bin/sed
> php_cv_cc_dashr=no
> php_cv_cc_rpath=yes
> php_cv_re2c_version='0.14.3 (ok)'
> 
> ## ----------------- ##
> ## Output variables. ##
> ## ----------------- ##
> 
> AR=''
> AWK='nawk'
> CC='cc'
> CFLAGS='-g -O2'
> CONFIGURE_COMMAND=' '\''./configure'\'' '
> CONFIGURE_OPTIONS=''
> CPP='cc -E'
> CPPFLAGS=' -I/usr/local/include -std=c++11'
> CXX='g++'
> CXXCPP='g++ -E'
> CXXFLAGS='-g -O2'
> DEFS=''
> DSYMUTIL=''
> ECHO='echo'
> ECHO_C=''
> ECHO_N='-n'
> ECHO_T=''
> EGREP='/usr/bin/grep -E'
> EXEEXT=''
> GREP='/usr/bin/grep'
> LDFLAGS=' -L/usr/local/lib'
> LIBOBJS=''
> LIBS='-lstdc++   -lv8_libplatform -lv8 -lv8_libbase -lv8_libplatform -lv8'
> LIBTOOL=''
> LN_S=''
> LTLIBOBJS=''
> NMEDIT=''
> OBJEXT='o'
> PACKAGE_BUGREPORT=''
> PACKAGE_NAME=''
> PACKAGE_STRING=''
> PACKAGE_TARNAME=''
> PACKAGE_URL=''
> PACKAGE_VERSION=''
> PATH_SEPARATOR=':'
> RANLIB=''
> RE2C='re2c'
> SED='/usr/bin/sed'
> SHELL='/bin/sh'
> SHLIB_DL_SUFFIX_NAME='so'
> SHLIB_SUFFIX_NAME='so'
> STRIP=''
> ac_ct_CC='cc'
> ac_ct_CXX='g++'
> bindir='${exec_prefix}/bin'
> build='amd64-unknown-freebsd11.0'
> build_alias=''
> build_cpu='amd64'
> build_os='freebsd11.0'
> build_vendor='unknown'
> datadir='${datarootdir}'
> datarootdir='${prefix}/share'
> docdir='${datarootdir}/doc/${PACKAGE}'
> dvidir='${docdir}'
> exec_prefix='NONE'
> host='amd64-unknown-freebsd11.0'
> host_alias='amd64-unknown-freebsd11.0'
> host_cpu='amd64'
> host_os='freebsd11.0'
> host_vendor='unknown'
> htmldir='${docdir}'
> includedir='${prefix}/include'
> infodir='${datarootdir}/info'
> libdir='${exec_prefix}/lib'
> libexecdir='${exec_prefix}/libexec'
> localedir='${datarootdir}/locale'
> localstatedir='${prefix}/var'
> mandir='${datarootdir}/man'
> oldincludedir='/usr/include'
> pdfdir='${docdir}'
> prefix='/usr/local'
> program_transform_name='s,x,x,'
> psdir='${docdir}'
> sbindir='${exec_prefix}/sbin'
> sharedstatedir='${prefix}/com'
> sysconfdir='${prefix}/etc'
> target='amd64-unknown-freebsd11.0'
> target_alias=''
> target_cpu='amd64'
> target_os='freebsd11.0'
> target_vendor='unknown'
> 
> ## ----------- ##
> ## confdefs.h. ##
> ## ----------- ##
> 
> /* confdefs.h */
> #define PACKAGE_NAME ""
> #define PACKAGE_TARNAME ""
> #define PACKAGE_VERSION ""
> #define PACKAGE_STRING ""
> #define PACKAGE_BUGREPORT ""
> #define PACKAGE_URL ""
> 
> configure: exit 1
>

**Comment by stesie** [comment]
```
configure:5035: g++ -o conftest -g -O2 -I/usr/local/include -std=c++11 -L/usr/local/lib conftest.cpp -lstdc++ -lv8_libplatform -lv8 >&5
/usr/local/bin/ld: /usr/local/lib/libv8_libplatform.a(default-platfor): undefined reference to symbol '_ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv'
//usr/lib/libc++.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

there's something wrong with the compilation as it reports undefined references to the standard library

please try saving the test program contents to `conftest.cpp`

```
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
namespace v8 {
namespace platform {
void CreateDefaultPlatform(int thread_pool_size = 0);
}
}
int
main ()
{
v8::platform::CreateDefaultPlatform();
;
return 0;
}
```

and then try changing the library linking order, especially try placing `-lstdc++` behing the V8 libraries

**Comment by sebbio** [comment]
same error

**Comment by stesie** [comment]
Sorry for the longish delay.  I've now installed FreeBSD 11 myself, to try and reproduce this.
I don't find a ready-to-use V8 package, where did you take your V8 library from?

Or did you compile yourself?

**Comment by stesie** [comment]
Update: I've found a port at https://raw.githubusercontent.com/Kronuz/Xapiand/master/contrib/freebsd/v8.shar

**Comment by stesie** [comment]
And regarding your problem, I'm pretty sure you've got the following problem (into which I also ran):

* you have two compilers installed: clang and gcc
* your C-compiler (`CC` variable) is `cc`, which is clang
* your C++ compiler (`CXX` variable) is `g++`, which is gcc

... combining the two, i.e. using gcc to compile and then clang to link doesn't work, as the clang linker will pull in a different c++ library ... and hence not work.

So if you want to keep both compilers installed, do `./configure CXX=c++` (supposing that c++ points to your clang c++ compiler); or maybe `./configure CC=gcc CXX=g++` (to use gcc/g++ for everything)
