### ISSUE TITLE
Cannot compile against latest V8 (5.9.35)

### ISSUE THREAD

**Issue by jakubkulhan** [phpv8/v8js#301]
`./configure` fails with:

```
checking for libv8_libplatform... checking for libv8_libplatform... configure: error: could not find libv8_libplatform library
```

Since 5.9.19 `v8::platform::CreateDefaultPlatform` has 2 parameters: https://github.com/v8/v8/blob/5.9.19/include/libplatform/libplatform.h

Check for `libv8_libplatform` uses old signature https://github.com/phpv8/v8js/blob/php7/config.m4#L90-L111

**Comment by stesie** [comment]
Yet the function has default arguments, so that shouldn't be the problem.
Please post your `config.log` file as it should have more details on what actually went wrong

**Comment by stesie** [comment]
Nah, scratch that. Shouldn't just look and answer from my phone. I'll have a closer look tomorrow

**Comment by jakubkulhan** [comment]
As far as I know, default parameters only mean that the when function is being called with less arguments, compiler looks up its declaration and tries to fill in missing arguments. 

Because check in `config.m4` does not include `libplatform.h`, but declares `CreateDefaultPlatform` itself with only single parameter, both names are mangled differently. Therefore linking fails.

**Comment by stesie** [comment]
@jakubkulhan yes, c++ symbol mangling is exactly what I forgot about when answering from my mobile ;-)

Yet currently I'm at work, will have a look tonight or so ...

**Comment by jakubkulhan** [comment]
Thank you! :)
