### ISSUE TITLE
new V8Js(); very slow on windows x64

### ISSUE THREAD

**Issue by marsiancba** [phpv8/v8js#312]
simple call to:

$v8 = new V8Js();

takes 400-500ms on fresh install of PHP on Windows x64.
Is this normal expected behavior?

Details below:
Windowx 10 x64
Builds from https://www.apachelounge.com/viewtopic.php?t=6359 (both 7.0 and 7.1 builds are slow).

Test code:

```
<?php
$t = microtime(true);
$v8 = new V8Js();
$t2 = microtime(true);
echo '<br>T: '.round($t2-$t,3).'<br>';
$v8->executeString("print('hello world');");
$tt = microtime(true);
echo '<br>T: '.round($tt-$t,3).'<br>';

echo '<br>v2</br>';

$t = microtime(true);
$v8 = new V8Js("PHP", [], []);
$t2 = microtime(true);
echo '<br>T: '.round($t2-$t,3).'<br>';
$v8->executeString("print('hello world');");
$tt = microtime(true);
echo '<br>T: '.round($tt-$t,3).'<br>';
?>
```

Output:

```
T: 0.46
hello world
T: 0.46

v2

T: 0.434
hello world
T: 0.434
```

**Comment by virgofx** [comment]
Can you build an older version using the exact same code to show the time differences? Also test different V8 versions as well.

**Comment by marsiancba** [comment]
I can not build V8js by myself, but I have checked one older build from the web:

https://github.com/maryo/php_v8js-1.2.0-7.0-vc14-x64

With this build I get times in range 50-100ms (but it had some other problem).

**Comment by stesie** [comment]
Seems like one of the builds is using snapshots and the other one doesn't.

**Comment by stesie** [comment]
No response, closing. Feel free to re-open with more information.
