### ISSUE TITLE
Return V8Object is endless iterable

### ISSUE THREAD

**Issue by HoffmannP** [phpv8/v8js#316]
The following script produces an endless steam of lines containing "test: test":

    <?php
    
    $jscript = new V8Js();
    $jscript->executeString("values = {}");
    $jscript->executeString("values['test'] = 'test'");
    $values = $jscript->executeString("values");
    
    foreach ($values as $key => $value) {
        echo "$key: $value\n";
    }

**Comment by stesie** [comment]
Nice catch :-)

PHP allows V8Js to refresh the properties after every round of iteration ... and V8js rebuilds the table from scratch every time (primarily to reflect properties being removed meanwhile), yet this resets the iterator heads

**Comment by HoffmannP** [comment]
Wow, this was fast!
