### ISSUE TITLE
Error with XAMPP for Windows

### ISSUE THREAD

**Issue by robertontiu** [phpv8/v8js#333]
Hey,

Since I installed the latest "Creators Update" for Windows the v8js extension stopped working. When I try to start Apache I get the following errors:

The procedure entry point ?hasMetaData@UnicodeString@icu_54@@UBECXZ could not be located in dynamic link library v8.dll

The procedure entry point ?matchesIndexValue@UnicodeSet@icu_54@@EBECE@Z could not be located in dynamic link library icui18n.dll

I am using this on my localhost development environment to render React server side with PHP. It is not a big issue as my production server is Linux (I assume it works there) but it would be nice to have it fixed at some point.

Thanks in advance.

**Comment by stesie** [comment]
I'm not a Windows guy, sorry ...

@Jan-E any idea on that one?

**Comment by 54huige** [comment]
Hello, can you tell me how to compile window v8js?

**Comment by amib77** [comment]
having same problem anyone find a solution?

**Comment by Webguru0920** [comment]
hello everyone.
I had same issue on windows xampp.
please try like this.
https://stackoverflow.com/questions/48203147/how-to-install-v8js-for-php-on-xampp-for-windows
