### ISSUE TITLE
fetch v8 failing 

### ISSUE THREAD

**Issue by stephan-v** [phpv8/v8js#337]
I am running:

```
lsb_release -a:

Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
```

I have issues with the `fetch v8` command is it giving me this error message:

```
Running: gclient sync --with_branch_heads
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /tmp
Traceback (most recent call last):
  File "/tmp/depot_tools/fetch.py", line 299, in <module>
    sys.exit(main())
  File "/tmp/depot_tools/fetch.py", line 294, in main
    return run(options, spec, root)
  File "/tmp/depot_tools/fetch.py", line 288, in run
    return checkout.init()
  File "/tmp/depot_tools/fetch.py", line 131, in init
    self.run_gclient(*sync_cmd)
  File "/tmp/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/tmp/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2
```

I is related to this issue where I found the same problem:

https://github.com/phpv8/v8js/issues/283

This issue suggested to run the command manually to see what the outcome would be.

If I run it manually I get the following error message:

```
0> Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format, skipping. [Err: /tmp/depot_tools/vpython: line 12: /tmp/depot_tools/.cipd_bin/vpython: No such file or directory
]
Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format. [Err: /tmp/depot_tools/vpython: line 12: /tmp/depot_tools/.cipd_bin/vpython: No such file or directory
]
```

I guess this is correct because in my `depot_tools` there is no file like that, it this because of the request with the `gs` protocol failing?

**Comment by stephan-v** [comment]
I installed `curl` after diggin through heaps of issues, because it somehow breaks silently without it(wtf?).

Perhaps it is a good idea to mention this as a requirement in the documentation?

It is running now, will update later.

**Comment by yusupprog** [comment]
getting same error, anyone know how to fix?

**Comment by stephan-v** [comment]
@yusupprog As mentioned I have to install curl on my machine because the files are fetched using curl.

See: https://github.com/phpv8/v8js/commit/b767fa4a4eb29f36d25754fb828a579a5344d928

**Comment by yusupprog** [comment]
I'm on Centos 7. And I have latest version of curl
`Package curl-7.29.0-42.el7_4.1.x86_64 already installed and latest version`

getting same error as you got

`Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format, skipping.`

`Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format.`

**Comment by yusupprog** [comment]
`Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format, skipping. [Err: /var/www/yusup/data/depot_tools/vpython: line 42`

`Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format. [Err: /var/www/yusup/data/depot_tools/vpython: line 42:`

**Comment by stephan-v** [comment]
It been a while since I have used this project, I guess there is nothing left but to check out the source code and see what is happening there. Perhaps try to manually use curl and see what it gives you.

**Comment by yusupprog** [comment]
![screen shot 2018-02-26 at 15 21 49](https://user-images.githubusercontent.com/11705239/36662495-ccf3aed8-1b08-11e8-9ba0-4ac8aab9715c.png)

Could be this the error?

**Comment by stesie** [comment]
@yusupprog I'd suppose that `download_from_google_storage` replaces the `gs://` part by something more meaningful, hence passing the raw url to curl directly, doesn't work

Maybe try running `download_from_google_storage` with `strace` to find out what it's trying to do.

Does the `/tmp/depot_tools/.cipd_bin/vpython` file exist? Maybe the library loader just tells it doesn't exist since a dependency is missing. Maybe try `ldd` on it.

**Comment by yusupprog** [comment]
There is no `depot_tools/.cipd_bin` directory
![screen shot 2018-02-26 at 17 31 28](https://user-images.githubusercontent.com/11705239/36668256-e6553790-1b1a-11e8-803d-98414ce07ac0.png)

**Comment by stesie** [comment]
:thinking: does it maybe extract it on the fly and delete afterwards? (but just guessing here, never had that problem)

**Comment by yusupprog** [comment]
I also thought that it creates it on the fly

**Comment by ally-petitt** [comment]
Hey everyone, 

I encountered this error as well. I had PiHole running, which was silently blocking the domain names that fetch was downloading from. I solved it by whitelisting the domain `chrome-infra-packages.appspot.com`.  

If that doesn't work, you can also try to temporarily disable DNS filtering to rule out that as an issue. You may need to delete and re-download depot-tools in order for these changes to work.

Edit: this error can also occur if you don't have adequate permissions on the depot-tools directory. As stated by [relrel in the AUR](https://aur.archlinux.org/packages/depot-tools-git#comment-773146):

> depot_tools is installed in /opt/depot_tools/. This directory is not in $PATH by default, so make 
> sure to export PATH=/opt/depot_tools:$PATH before using it. Also, this directory has root permissions, so either use it as root, or if you want to use it as your currect user:
> 
> ```
> groupadd depot_tools
> # gpasswd -a $(whoami) depot_tools
> # setfacl -m g:depot_tools:rwX /opt/depot_tools/
> ```
> Then re-login as your current user or log your terminal in to the newly created group:
> 
> ```
> $ newgrp depot_tools
> ```



Best of luck,
Ally
