### ISSUE TITLE
Symbol lookup error[Debian]

### ISSUE THREAD

**Issue by stephan-v** [phpv8/v8js#338]
I have installed the v8 engine, compiled everything and am trying to test it out through my CLI now. I am running into this error:

> symbol lookup error: /usr/lib/php/20160303/v8js.so: undefined symbol: _ZNSt6chrono3_V212system_clock3nowEv

I am having a hard time trying to find more information about this. Any help would be appreciated to try and get this up and running. Thanks. 

My `lsb_release -a`:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
```

**Comment by stesie** [comment]
Try passing `LDFLAGS="-lstdc++"` to the `./configure` call
