### ISSUE TITLE
Module loader doesn't allow relative paths

### ISSUE THREAD

**Issue by tillsanders** [phpv8/v8js#343]
I've been trying to implement my own module loader (simulating the behaviour of node) using `setModuleLoader()` and `setModuleNormaliser()`. The callback I wrote for `setModuleNormaliser()` gets two arguments:

1. base path of the current **module**
2. the literate string provided to the require method

Now, if the required path is relative (e.g. `./some-sub-module.js`), I have no way of finding this required file because my callback only knows the base path of the current module, but not the path of the current file.

**Comment by stesie** [comment]
You should use the normaliser callback to map from module name to filepath, then you can interpret relative paths in subsequent calls correctly.

See https://gist.github.com/stesie/c9143b98355295420470 for a Node.js module loader implementation.
(that at least can load .js files; fails on .json files though)

**Comment by chenos** [comment]
Might as well try this:

https://github.com/chenos/v8js-module-loader
