### ISSUE TITLE
Deprecating old pinepain/libv8 PPAs

### ISSUE THREAD

**Issue by pinepain** [phpv8/v8js#345]
Hi @stesie!

Short version:

some libv8 PPAs are deprecated, their content archived and moved to new PPA and original PPAs will be removed in spring 2018.

TL;DR

I know that some of v8js clients depends on `pinepain/libv8-X.Y` PPAs I maintain, so I'd like to give you a heads up on deprecating old and longer maintained v8 versions:

In short, as of now I'm deprecating everything below current stable v8 (https://omahaproxy.appspot.com/) - 2 versions behind, which means everything starting down from 6.0 is deprecated:

 - libv8-4.10
 - libv8-5.1
 - libv8-5.2
 - libv8-5.4
 - libv8-5.7
 - libv8-5.8
 - libv8-5.9
 - libv8-6.0

I noticed that in your repo you depends on 5.7 5.8 5.9 6.0, which all are subject of deprecation.

Though, no worries, all deprecated repos are merged into [libv8-archived](https://launchpad.net/~pinepain/+archive/ubuntu/libv8-archived) PPA and it will be available until further notice (I don't have specific date for starting removing old v8 versions for now). Current deprecated repos will still be available for the next few month - I plan to shut them down completely no earlier than sprint 2018.

I propose to scale down variety of v8 versions you support or utilize new `pinepain/libv8-archived` PPA for old versions.

Please, let me know if you or/and your users need more time to adopt/discuss this changes.

**Comment by stesie** [comment]
Hey @pinepain,

thanks for letting me know. I've just updated Travis configuration to use recent V8 versions to execute the tests, and will try to keep that up-to-date in the future :)

And I think it's a good idea to scale down on supported V8 versions.

**Comment by stesie** [comment]
Gah, build failed since 6.5 isn't available on Trusty.  Will change Travis to use Xenial instead of Trusty soonish :)

**Comment by pinepain** [comment]
Base on recent CPUs speculative execution vulnerability, I'm updating libv8 6.4 and 6.5 with a security fix as per https://github.com/v8/v8/wiki/Untrusted-code-mitigations.

As it means that any versions < 6.4 is less likely to get such updates, so I'm deprecating 6.1, 6.2 and 6.3 in the same manner. They will all be available for some time and they already copied to `pinepain/libv8-archived`. 

Sorry for any inconvenience.
