### ISSUE TITLE
Hi. getting error installing v8js for php7 through brew on mac

### ISSUE THREAD

**Issue by yusupprog** [phpv8/v8js#361]
```Error: No available formula with the name "php71-v8js"```

**Comment by kynx** [comment]
You probably want to ask brew about this, but fwiw they aren’t shipping formulas for php extensions any longer. 

See https://brew.sh/2018/01/19/homebrew-1.5.0/ - they now recommend installing via pecl.

**Comment by yusupprog** [comment]
Thank you. Manually compiled it and now it works.
