### ISSUE TITLE
Backport changes for PHP 7.2 compatibility to a 1.3.7 branch?

### ISSUE THREAD

**Issue by TysonAndre** [phpv8/v8js#366]
Currently, I'm holding this back to 1.3.x because of issues I saw when upgrading libv8. (1.4 would require upgrading libv8)

https://github.com/TysonAndre/v8js/commits/backport-1.3.7 is a branch you can use that applies only the php 7.2 compatibility patch, and bumps the version from 1.3.6 to 1.3.7 and updates package.xml (https://github.com/TysonAndre/v8js/releases/tag/1.3.7 are example release notes)

**Comment by stesie** [comment]
Hey, I'm not aware (yet haven't tried) that there was a change in compatibility regarding older V8 versions. Let me know if the 4.6.76 build is broken (or whichever you use) and we'll see.

Anyways you likely shouldn't use those old V8 versions as they don't have security support anyhow...
