### ISSUE TITLE
Fedora 28, PHP 7.2, v8js does not load

### ISSUE THREAD

**Issue by starvsion** [phpv8/v8js#375]
Hi:

OS: Fedora 28;
PHP: 7.2.9
V8: 1:6.7.17-7.fc28
V8JS: 2.1.0-1.fc28.remi.7.2

I am using v8 from offical Fedora repository, and php-pecl-v8js from remi, and this is the error I am getting: 

`PHP Warning:  PHP Startup: Unable to load dynamic library 'v8js.so' (tried: /usr/lib64/php/modules/v8js.so (/usr/lib64/php/modules/v8js.so: undefined symbol: _ZN2v87Context3NewEPNS_7IsolateEPNS_22ExtensionConfigurationENS_10MaybeLocalINS_14ObjectTemplateEEENS5_INS_5ValueEEE), /usr/lib64/php/modules/v8js.so.so (/usr/lib64/php/modules/v8js.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

If I use PECL, then, this is the error message I get: 
```
downloading v8js-2.1.0.tgz ...
Starting to download v8js-2.1.0.tgz (101,553 bytes)
.......................done: 101,553 bytes
28 source files, building
running: phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
Please provide the installation prefix of libv8 [autodetect] :
building in /var/tmp/pear-build-idtyuSbX70b/v8js-2.1.0
running: /var/tmp/v8js/configure --with-php-config=/usr/bin/php-config --with-v8js
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.14.3 (ok)
checking for gawk... gawk
checking for V8 Javascript Engine... yes, shared
checking for V8 files in default path... not found
configure: error: Please reinstall the v8 distribution
ERROR: `/var/tmp/v8js/configure --with-php-config=/usr/bin/php-config --with-v8js' failed
```

Is this a bug or I am supposed to use other versions of PHP or V8 ? Thanks

**Comment by stesie** [comment]
Generally, using different V8 versions at compile and runtime does *not* work well with V8. So if you're using the ext-v8js package by @remicollet, then you also need to use the V8 rpm package he used while packaging. I don't know which this is, ... since it's not working, probably not.

Regarding the PECL configuration error, please have a look into `config.log` file, towards the end it should have a more detailed error message on what went wrong

**Comment by remicollet** [comment]
The extension was built in Feb... so against v8 6.2.91 [1]
But v8 was updated to 6.7.17 later (April), such thing should not happen in Fedora... :(

I have run a new set of build to ensure we use the same version at buildtime and runtime
`php-pecl-v8js-2.1.0-2.fc28.remi.7.2` should fix this issue (at least test suite passes)


[1] https://rpms.remirepo.net/rpmphp/zoom.php?rpm=v8

**Comment by remicollet** [comment]
Notice, issue with my package should probably be reported first on https://github.com/remicollet/remirepo/issues
