### ISSUE TITLE
Ubuntu 18 configure: error: could not determine libv8 version

### ISSUE THREAD

**Issue by TheRatG** [phpv8/v8js#384]
Hello,
I try to compile v8js to Ubuntu18 but i have an error :
```
checking for V8 version... NONE
configure: error: could not determine libv8 version
```

#### Steps:
```
add-apt-repository ppa:stesie/libv8
apt-get update -y
apt-get install libv8-7.1-dev -y
cd /tmp
git clone https://github.com/phpv8/v8js.git
cd v8js
phpize
./configure --with-v8js=/opt/libv8-7.1 LDFLAGS="-lstdc++"
```

#### Debug info

[config.log](https://github.com/phpv8/v8js/files/2594395/config.log)

```bash
# ldd /opt/libv8-7.1/lib/*.so  | grep 'not found'
	libv8_libbase.so => not found
	libv8_libbase.so => not found
```

Thanks.

**Comment by TheRatG** [comment]
Problem was [solved](https://github.com/phpv8/v8js/issues/335#issuecomment-355653984).

So before install php-extension run this.

```
apt-get install patchelf
for A in /opt/libv8-7.1/lib/*.so; do patchelf --set-rpath '$ORIGIN' $A;done
```

**Comment by stesie** [comment]
Oh, interesting :) ... just tried the packages on xenial so far, and there it works fine without patching.
