### ISSUE TITLE
The newer version of V8 cannot compile v8js

### ISSUE THREAD

**Issue by turnmind** [phpv8/v8js#389]
> [root@localhost ~]# pecl install v8js
downloading v8js-2.1.0.tgz ...
Starting to download v8js-2.1.0.tgz (101,553 bytes)
.......................done: 101,553 bytes
28 source files, building
running: phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
Please provide the installation prefix of libv8 [autodetect] : /opt/v8
building in /tmp/pear/temp/pear-build-rootbY9pe5/v8js-2.1.0
running: /tmp/pear/temp/v8js/configure --with-php-config=/usr/local/php/bin/php-config --with-v8js=/opt/v8
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 1.0.1 (ok)
checking for gawk... gawk
checking for V8 Javascript Engine... yes, shared
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for C standard version... c++11
checking how to allow c++11 narrowing...
checking for libv8_libplatform... found
checking for V8 version... 7.3.0
checking for natives_blob.bin... found (/opt/v8/lib/natives_blob.bin)
checking for snapshot_blob.bin... found (/opt/v8/lib/snapshot_blob.bin)
checking for v8::ArrayBuffer::Allocator::NewDefaultAllocator... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /tmp/pear/temp/pear-build-rootbY9pe5/v8js-2.1.0/libtool --mode=compile g++  -std=c++11 -I. -I/tmp/pear/temp/v8js -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootbY9pe5/v8js-2.1.0/include -I/tmp/pear/temp/pear-build-rootbY9pe5/v8js-2.1.0/main -I/tmp/pear/temp/v8js -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/opt/v8/include -I/opt/v8  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/v8js/v8js_array_access.cc -o v8js_array_access.lo
mkdir .libs
 g++ -std=c++11 -I. -I/tmp/pear/temp/v8js -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootbY9pe5/v8js-2.1.0/include -I/tmp/pear/temp/pear-build-rootbY9pe5/v8js-2.1.0/main -I/tmp/pear/temp/v8js -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/opt/v8/include -I/opt/v8 -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/v8js/v8js_array_access.cc  -fPIC -DPIC -o .libs/v8js_array_access.o
In file included from /opt/v8/include/v8-internal.h:13:0,
                 from /opt/v8/include/v8.h:25,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8config.h:307:49: 警告：不建议使用‘BufferReference’(声明于 /opt/v8/include/v8.h:4345)：Use MemorySpan<const uint8_t> [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/opt/v8/include/v8.h:4403:3: 附注：in expansion of macro ‘V8_DEPRECATED’
   V8_DEPRECATED("Use CompiledWasmModule::GetWireBytesRef()",
   ^
/opt/v8/include/v8config.h:307:49: 警告：不建议使用‘v8::WasmModuleObject::SerializedModule’(声明于 /opt/v8/include/v8.h:4339)：Use OwnedBuffer [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/opt/v8/include/v8.h:4416:3: 附注：in expansion of macro ‘V8_DEPRECATED’
   V8_DEPRECATED("Use CompiledWasmModule::Serialize()",
   ^
In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:55:0,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/tmp/pear/temp/v8js/v8js_array_access.cc: 在函数‘void v8js_array_access_enumerator(const v8::PropertyCallbackInfo<v8::Array>&)’中:
/tmp/pear/temp/v8js/v8js_v8.h:23:57: 警告：不建议使用‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’(声明于 /opt/v8/include/v8.h:2754)：Use maybe version [-Wdeprecated-declarations]
 #define V8JS_STR(v)   v8::String::NewFromUtf8(isolate, v)
                                                         ^
/tmp/pear/temp/v8js/v8js_array_access.cc:217:14: 附注：in expansion of macro ‘V8JS_STR’
  result->Set(V8JS_STR("length"), V8JS_INT(i));
              ^
/tmp/pear/temp/v8js/v8js_array_access.cc: 在函数‘void v8js_array_access_named_getter(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’中:
/tmp/pear/temp/v8js/v8js_array_access.cc:226:37: 错误：对‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::String>&)’的调用没有匹配的函数
  v8::String::Utf8Value cstr(property);
                                     ^
/tmp/pear/temp/v8js/v8js_array_access.cc:226:37: 附注：备选是：
In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:52:0,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:2859:5: 附注：v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^
/opt/v8/include/v8.h:2859:5: 附注： 备选需要 2 实参，但提供了 1 个
/tmp/pear/temp/v8js/v8js_array_access.cc:246:35: 错误：对‘v8::Value::ToObject()’的调用没有匹配的函数
   ret_value = prototype->ToObject()->Get(property);
                                   ^
/tmp/pear/temp/v8js/v8js_array_access.cc:246:35: 附注：备选是：
In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:52:0,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:2392:44: 附注：v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^
/opt/v8/include/v8.h:2392:44: 附注： 备选需要 1 实参，但提供了 0 个
In file included from /opt/v8/include/v8-internal.h:13:0,
                 from /opt/v8/include/v8.h:25,
                 from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
                 from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
/opt/v8/include/v8.h:2406:35: 附注：v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/opt/v8/include/v8config.h:329:48: 附注：in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/opt/v8/include/v8.h:2406:35: 附注： 备选需要 1 实参，但提供了 0 个
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/opt/v8/include/v8config.h:329:48: 附注：in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
make: *** [v8js_array_access.lo] 错误 1
ERROR: `make' failed

**Comment by koriym** [comment]
Same error ?
https://gist.github.com/koriym/a4e0921e69d874b3e374cfffce1a1a5d

**Comment by youaresodalgona** [comment]
I had the same problem.

**Comment by stesie** [comment]
Would someone of you like to have a closer look into this and possibly open a pull request?

From the error output it looks like the API has been changed (again) by adding `isolate` arguments; and usually the isolate is already available in the calling function. You could also have a look into former fixes to those problems.

Anyways thanks for pointing out there is a problem :)

... cannot tell when I've got time to have a look myself

**Comment by grimpows** [comment]
same here with a v8 7.2.502.25 (supposed to be the last stable one from https://omahaproxy.appspot.com/)
Note that i dont use pecl but  **./configure --with-v8js=/opt/v8 LDFLAGS="-lstdc++"** from git (checkout to **2.1.0**).
Actually  i use the v8 (6.6.155) and that's work well, but dont know if the prob came from v8js or v8 himself (who is suposed to be "stable")

**Comment by stesie** [comment]
There now is v8js 2.1.1 which supports V8 7.x line, especially the current stable release 7.5 is known to work fine
