### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ghost** [phpv8/v8js#391]
`Fatal error: Uncaught exception 'V8JsException' with message 'V8Js::executeString():1: ReferenceError: document is not defined' in /var/www/html/get_ip.php:26 Stack trace: #0 /var/www/html/get_ip.php(26): V8Js->executeString('document.write(...') #1 {main} thrown in /var/www/html/get_ip.php on line 26`

  ```
  $v8 = new V8Js();
    $portxo = $v8->executeString("document.write(Xinemara^Xinemara^1080)");
```

any help with this?

**Comment by stesie** [comment]
What do you expect?  Javascript does not specify `document`, that belongs to your browser's API/DOM
