### ISSUE TITLE
php 7.3 compatibility

### ISSUE THREAD

**Issue by rbro** [phpv8/v8js#392]
I just wanted to find out the status of php 7.3 compatibility.  Would it be possible to release a new version to pecl if it's ready?  I'm happy to help test if needed.

Thanks for your help.

**Comment by tschaible** [comment]
Seconded this request.  It looks like past issues noting PHP 7.3 compatibility have been resolved, but there's no release with those changes.

It's difficult to tell if those changes are considered stable/ready or if further work is planned.  

I'm also happy to help test though.

**Comment by stesie** [comment]
Sorry for it to have taken me so long.  But finally the release 2.1.1 is there :)

**Comment by rbro** [comment]
Thanks so much!  I appreciate all your work on v8js.  With the new version, I'm just now running into the same issue mentioned in #406 about trying to compile a newer version of v8 on CentOS 7 and getting errors about GLIBCXX_3.4.20 and GLIBCXX_3.4.21 not found.

**Comment by Reforced** [comment]
>  issue mentioned in #406 about trying to compile a newer version of v8 on CentOS 7 and getting errors about GLIBCXX_3.4.20 and GLIBCXX_3.4.21 not found.



+1
