### ISSUE TITLE
Error while compiling. Pecl install v8js - php 7.2.15

### ISSUE THREAD

**Issue by ShinJii89** [phpv8/v8js#394]
Hi,
I have an error while `pecl install v8js`

> WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
> downloading v8js-2.1.0.tgz ...
> Starting to download v8js-2.1.0.tgz (101,553 bytes)
> .....done: 101,553 bytes
> 28 source files, building
> running: phpize72
> Configuring for:
> PHP Api Version:         20170718
> Zend Module Api No:      20170718
> Zend Extension Api No:   320170718
> Please provide the installation prefix of libv8 [autodetect] : /opt/v8
> building in /tmp/pear/temp/pear-build-rootfpTVYg/v8js-2.1.0
> running: /tmp/pear/temp/v8js/configure --with-php-config=/usr/local/php72/bin/php-config72 --with-v8js=/opt/v8
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for a sed that does not truncate output... /usr/bin/sed
> checking for cc... cc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for PHP prefix... /usr/local/php72
> checking for PHP includes... -I/usr/local/php72/include/php -I/usr/local/php72/include/php/main -I/usr/local/php72/include/php/TSRM -I/usr/local/php72/include/php/Zend -I/usr/local/php72/include/php/ext -I/usr/local/php72/include/php/ext/date/lib
> checking for PHP extension directory... /usr/local/php72/lib/php/extensions/no-debug-non-zts-20170718
> checking for PHP installed headers prefix... /usr/local/php72/include/php
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... no
> configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
> checking for gawk... gawk
> checking for V8 Javascript Engine... yes, shared
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking how to run the C++ preprocessor... g++ -E
> checking for C standard version... c++11
> checking how to allow c++11 narrowing...
> checking for libv8_libplatform... found
> checking for V8 version... 7.4.0
> checking for natives_blob.bin... found (/opt/v8/lib/natives_blob.bin)
> checking for snapshot_blob.bin... found (/opt/v8/lib/snapshot_blob.bin)
> checking for v8::ArrayBuffer::Allocator::NewDefaultAllocator... yes
> checking for ld used by cc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for /usr/bin/ld option to reload object files... -r
> checking for BSD-compatible nm... /usr/bin/nm -B
> checking whether ln -s works... yes
> checking how to recognize dependent libraries... pass_all
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking dlfcn.h usability... yes
> checking dlfcn.h presence... yes
> checking for dlfcn.h... yes
> checking how to run the C++ preprocessor... g++ -E
> checking the maximum length of command line arguments... 1572864
> checking command to parse /usr/bin/nm -B output from cc object... ok
> checking for objdir... .libs
> checking for ar... ar
> checking for ranlib... ranlib
> checking for strip... strip
> checking if cc supports -fno-rtti -fno-exceptions... no
> checking for cc option to produce PIC... -fPIC
> checking if cc PIC flag -fPIC works... yes
> checking if cc static flag -static works... no
> checking if cc supports -c -o file.o... yes
> checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> 
> creating libtool
> appending configuration tag "CXX" to libtool
> checking for ld used by g++... /usr/bin/ld -m elf_x86_64
> checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking for g++ option to produce PIC... -fPIC
> checking if g++ PIC flag -fPIC works... yes
> checking if g++ static flag -static works... no
> checking if g++ supports -c -o file.o... yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... GNU/Linux ld.so
> (cached) (cached) checking how to hardcode library paths into programs... immediate
> configure: creating ./config.status
> config.status: creating config.h
> running: make
> /bin/sh /tmp/pear/temp/pear-build-rootfpTVYg/v8js-2.1.0/libtool --mode=compile g++  -std=c++11 -I. -I/tmp/pear/temp/v8js -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootfpTVYg/v8js-2.1.0/include -I/tmp/pear/temp/pear-build-rootfpTVYg/v8js-2.1.0/main -I/tmp/pear/temp/v8js -I/usr/local/php72/include/php -I/usr/local/php72/include/php/main -I/usr/local/php72/include/php/TSRM -I/usr/local/php72/include/php/Zend -I/usr/local/php72/include/php/ext -I/usr/local/php72/include/php/ext/date/lib -I/opt/v8/include -I/opt/v8  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/v8js/v8js_array_access.cc -o v8js_array_access.lo
> mkdir .libs
>  g++ -std=c++11 -I. -I/tmp/pear/temp/v8js -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootfpTVYg/v8js-2.1.0/include -I/tmp/pear/temp/pear-build-rootfpTVYg/v8js-2.1.0/main -I/tmp/pear/temp/v8js -I/usr/local/php72/include/php -I/usr/local/php72/include/php/main -I/usr/local/php72/include/php/TSRM -I/usr/local/php72/include/php/Zend -I/usr/local/php72/include/php/ext -I/usr/local/php72/include/php/ext/date/lib -I/opt/v8/include -I/opt/v8 -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/v8js/v8js_array_access.cc  -fPIC -DPIC -o .libs/v8js_array_access.o
> In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:55:0,
>                  from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
> /tmp/pear/temp/v8js/v8js_array_access.cc: In function ‘void v8js_array_access_enumerator(const v8::PropertyCallbackInfo<v8::Array>&)’:
> /tmp/pear/temp/v8js/v8js_v8.h:23:57: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated (declared at /opt/v8/include/v8.h:2894): Use maybe version [-Wdeprecated-declarations]
>  #define V8JS_STR(v)   v8::String::NewFromUtf8(isolate, v)
>                                                          ^
> /tmp/pear/temp/v8js/v8js_array_access.cc:217:14: note: in expansion of macro ‘V8JS_STR’
>   result->Set(V8JS_STR("length"), V8JS_INT(i));
>               ^
> /tmp/pear/temp/v8js/v8js_array_access.cc: In function ‘void v8js_array_access_named_getter(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’:
> /tmp/pear/temp/v8js/v8js_array_access.cc:226:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::String>&)’
>   v8::String::Utf8Value cstr(property);
>                                      ^
> /tmp/pear/temp/v8js/v8js_array_access.cc:226:37: note: candidate is:
> In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:52:0,
>                  from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
> /opt/v8/include/v8.h:2999:5: note: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
>      Utf8Value(Isolate* isolate, Local<v8::Value> obj);
>      ^
> /opt/v8/include/v8.h:2999:5: note:   candidate expects 2 arguments, 1 provided
> /tmp/pear/temp/v8js/v8js_array_access.cc:246:35: error: no matching function for call to ‘v8::Value::ToObject()’
>    ret_value = prototype->ToObject()->Get(property);
>                                    ^
> /tmp/pear/temp/v8js/v8js_array_access.cc:246:35: note: candidates are:
> In file included from /tmp/pear/temp/v8js/php_v8js_macros.h:52:0,
>                  from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
> /opt/v8/include/v8.h:2536:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
>    V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
>                                             ^
> /opt/v8/include/v8.h:2536:44: note:   candidate expects 1 argument, 0 provided
> In file included from /opt/v8/include/v8-internal.h:13:0,
>                  from /opt/v8/include/v8.h:25,
>                  from /tmp/pear/temp/v8js/php_v8js_macros.h:52,
>                  from /tmp/pear/temp/v8js/v8js_array_access.cc:17:
> /opt/v8/include/v8.h:2550:35: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
>                      Local<Object> ToObject(Isolate* isolate) const);
>                                    ^
> /opt/v8/include/v8config.h:329:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
>  #define V8_DEPRECATE_SOON(message, declarator) declarator
>                                                 ^
> /opt/v8/include/v8.h:2550:35: note:   candidate expects 1 argument, 0 provided
>                      Local<Object> ToObject(Isolate* isolate) const);
>                                    ^
> /opt/v8/include/v8config.h:329:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
>  #define V8_DEPRECATE_SOON(message, declarator) declarator
>                                                 ^
> make: *** [v8js_array_access.lo] Błąd 1
> ERROR: `make' failed

**Comment by ShinJii89** [comment]
Now I see it's the same problem like here - https://github.com/phpv8/v8js/issues/389 any idea when it will be fixed?

**Comment by timothympace** [comment]
I think you might get past this if you use master instead of 2.1.0. I ran into this same issue.

**Comment by jrmgx** [comment]
@timothympace how can you do that?

**Comment by timothympace** [comment]
Compile v8js from source using master branch. here's some instructions for compiling v8js: https://github.com/phpv8/v8js/blob/php7/README.Linux.md

**Comment by jrmgx** [comment]
Still having the issue with master branch

**Comment by ShahanurSharif** [comment]
I am having same issue

**Comment by stesie** [comment]
The last release version (2.1.0) doesn't support V8 7.x; so if you're trying 2.1.0 with that, it's known to fail.  A new release is upcoming ...

If you're trying with master, 7.x should be supported (< 7.5 should be working for quite a while); 7.5 known to work with master since yesterday.  So if you're still having trouble (w/ master), tell which V8 version you're trying with and provide excerpts from config.log (showing what actually caused the problem)

**Comment by stesie** [comment]
2.1.1 released right now, let me know if it works for you now

**Comment by ShahanurSharif** [comment]
still dont work.

**Comment by temuri416** [comment]
@stesie 

Any chance to look at the problem? Thanks!

**Comment by stesie** [comment]
On what system are you on?  Centos?  I know of some problems there (so someone contributed instructions over here: https://github.com/phpv8/v8js/wiki/Installing-on-CentOS-7-x64---PHP-7.3)

Otherwise, the build errors from above should be gone.  If it still goes wrong for you, please provide error output along which system you're trying to build on and with which V8 version
