### ISSUE TITLE
PHP does not catch throwing from inside a JS promise, async functions

### ISSUE THREAD

**Issue by GytisT** [phpv8/v8js#398]
Hello,

As title states, I cannot seem to trigger a PHP exception from within a JS promise and async functions.

Example:
`
$v8js->executeString("new Promise(function(resolve, reject) { reject(new Error('rejected')); }).then(function(response) { print(response); }).catch(function(e) { throw e; }); ");`

It just returns nothing at all.

I have struggled with this for a second day now. Tried all sorts of variations of throw, catch, etc.
However, throwing from within a regular function does trigger a PHP exception.

I am using PHP 7.3, latest compiled v8js php7 branch with v8 7.4

**Comment by GytisT** [comment]
Nevermind, this was my fault. Somehow it has completely gone past my head, that I am not waiting for promise to resolve but just creating one...
Anyway, I have fixed the issue by passing promise back to PHP side and using then callback.

**Comment by natewallis** [comment]
Can you give an example of how you pass promise back to PHP and handle then on PHP side?  I can't see any docs about this.
