### ISSUE TITLE
could not find libv8_libplatform library on php7.2

### ISSUE THREAD

**Issue by artemoleksiuk** [phpv8/v8js#400]
Hello, can you help me, please?
I have some error, but can't understand, what and where path should I write
I have macos

Trace:
checking for libv8_libplatform... configure: error: could not find libv8_libplatform library

**Comment by ShahanurSharif** [comment]
I am having same issue in php7.2

**Comment by stesie** [comment]
Recent instructions on how to build on MacOS are written down here: https://github.com/phpv8/v8js/issues/380#issuecomment-494561788

If that doesn't help, please tell at least which version of php-v8js and V8 you're trying to use. And please provide excerpt from config.log which tells what lead to the error
