### ISSUE TITLE
Compiling v8/v8js instructions for MacOS outdated

### ISSUE THREAD

**Issue by lamesensei** [phpv8/v8js#401]
Hi, I'm trying to install use v8js via pecl but I cant get the correct compile(?) files for the pecl command (pecl install v8js)

I've tried brew's v8; compiling v8 with linux and other instructions (gn with-component-build true) but none of them work... the old make instructions do not even start (no make target error)

**Comment by usback** [comment]
i want to use  my project v8js but do not working os mac and linux .

https://github.com/phpv8/v8js/blob/php7/README.Linux.md
https://github.com/phpv8/v8js/blob/php7/README.MacOS.md
it do not compile everything.
pecel intsall v8js -> same error.
 
do anybody know about install v8js ????

**Comment by exactmultiple3425** [comment]
I already gave up because of the difficulty of installing and use nginx upstream to a node server instead

**Comment by spoonscen** [comment]
It appears the makefile is missing for the MacOs.md install.

```
make native library=shared -j8
make: *** No rule to make target `native'.  Stop.
```

**Comment by noogen** [comment]
Updated instruction here: https://github.com/phpv8/v8js/issues/380#issuecomment-494561788
