### ISSUE TITLE
libv8_libplatform configure error with docker php-apache

### ISSUE THREAD

**Issue by jlwalkerlg** [phpv8/v8js#403]
I am trying to build a Docker image from [the official php docker image](https://hub.docker.com/_/php) (specifically I am using the php:7.3.4-apache version) with the v8js extension enabled. I keep running into an error when v8js is being installed with PECL.

Here is my Dockerfile:
```
FROM php:7.3.4-apache

# Install v8js
RUN apt-get update && apt-get install -y libv8-dev
RUN pecl install v8js-2.1.0 && docker-php-ext-enable v8js
```

`libv8-dev` installs successfully, as far as I can tell, but the `pecl install v8js-2.1.0` fails with the following output:
```
...
checking for V8 Javascript Engine... yes, shared
checking for V8 files in default path... found in /usr
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for C standard version... c++11
checking how to allow c++11 narrowing... -Wno-narrowing
checking for libv8_libplatform... configure: error: could not find libv8_libplatform library
ERROR: `/tmp/pear/temp/v8js/configure --with-php-config=/usr/local/bin/php-config --with-v8js' failed
The command '/bin/sh -c pecl install v8js-2.1.0 && docker-php-ext-enable v8js' returned a non-zero code: 1
```

I've searched through similar issues people are having with `libv8_libplatform` not being found but they are all using different setups (i.e. not using the php Docker image) and I am not familiar enough with Linux to piece together a solution, so would appreciate any help I can get. Thanks

**Comment by stesie** [comment]
which version of V8 do you have installed? Any special APT repo?  Since Debian ships 3.14.5

With phpv8 2.1.0 you should use some V8 from the 6.x line

**Comment by jlwalkerlg** [comment]
/usr/lib contains libv8.so.3.14.5, so I guess I do have 3.14.5. How would I go about installing a 6.x version from my Dockerfile? Or which phpv8 version should I download that works with V8 3.14.5, (since this is probably a lot easier)?

**Comment by kingwill101** [comment]
@jlwalkerlg did you get through on this? trying to get it installed with the official php image but unable to

**Comment by jlwalkerlg** [comment]
@glenfordwilliams I couldn't get it to work in the end but I did get a bit further than the issue I was having here. PECL wasn't working so I followed the [instructions for Linux](https://github.com/phpv8/v8js/blob/php7/README.Linux.md) and managed to get most of the way there. I can't remember what other issues I ran into though. The problem is that it takes so long to compile and install manually that you can only try so much in a given day.

Anyway if you manage to get it working please let me know how you did it. If you follow the instructions I linked remember that you don't need `sudo` with Docker, and don't run each command with a separate Docker `RUN` statement like I was doing at first, otherwise it will build a series of isolated containers that won't have access to the downloads you made in other containers -- instead, chain the commands together with `&&`. Also, the official php image uses Debian Stretch so follow the instruction about setting the RPATH too.

**Comment by noogen** [comment]
1.  You need to build v8: https://github.com/niiknow/docker-hostingbase/blob/master/v8build/Dockerfile and copy it to `/opt/libv8-7.4` or whatever libv8 version you built.

v8 can take a long time to build and may timeout if you build on docker hub, so I pre-built my binary and add to docker: https://github.com/niiknow/docker-hostingbase/blob/f3487048f8322a70685208680dbd59968e0e0c1b/Dockerfile#L5

Don't use my binary because your linux distro may require you to build a different binary.

2.  Then git clone and build v8js
```
git clone https://github.com/phpv8/v8js.git /tmp/v8js \
    && cd /tmp/v8js \
    && git checkout php7 && phpize7.3 \
    && ./configure LDFLAGS="-lstdc++" --with-v8js=/opt/libv8-7.4 \
   && make all test install
```

Example, I build it with php7.1-7.3: https://github.com/niiknow/docker-hostingbase/blob/f3487048f8322a70685208680dbd59968e0e0c1b/Dockerfile#L31

Also, 2.1.0 may not be compatible with higher v8 version and php7.3 so that's why you want to clone from the repo.
