### ISSUE TITLE
Could not find libv8_libplatform library

### ISSUE THREAD

**Issue by MuhajirulFaqih** [phpv8/v8js#404]
I try install v8js, but I found error like this "Could not find libv8_libplatform library".
Can anyone help me?

**Comment by uchqur** [comment]
Hello friend . I have same problems.

**Comment by innerdev** [comment]
Same here. Tyring to solve it for 6 hours.

**Comment by innerdev** [comment]
@MuhajirulFaqih can you help us, please, sir?

**Comment by ianmustafa** [comment]
@MuhajirulFaqih can you please provide your installation steps for us to reproduce the error?

**Comment by usback** [comment]
[v8.tar.gz](https://github.com/phpv8/v8js/files/3154048/v8.tar.gz)
this v8 engine can use x86 (64bit ) linux server

**Comment by ghost** [comment]
For me this turned out to be the solution: https://github.com/phpv8/v8js/issues/397#issuecomment-465218484

**Comment by Reforced** [comment]
I had the same problem on CentOS 7 (Attempting to install the latest v8 on PHP 7.3). After hours of (re)building attempts and reading various topics I've found the solution that worked for me: **Update the GCC/G++ package**. To see if this might be your problem as well, check your version via `gcc --version`.

Version working for me:
![image](https://user-images.githubusercontent.com/28508541/61030527-ddfcf600-a3bd-11e9-898e-d044fe6cc9c1.png)

Upgrading was as easy as:

```
sudo yum install centos-release-scl
sudo yum install devtoolset-7-gcc*
scl enable devtoolset-7 bash
which gcc
gcc --version
```

Then just following the steps outlined on https://github.com/phpv8/v8js/blob/php7/README.Linux.md. I hope this might help someone else too.

**Comment by diogoca** [comment]
Same here

**Comment by jhlater** [comment]
Same here.

**Comment by gkweb** [comment]
Same problem here with the pecl installation
