### ISSUE TITLE
Unable to install macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by palfaro91** [phpv8/v8js#407]
Hello, I am unable to install v8js following the instructions in the macOS readme. I skip the optional part about checking out a specific version and I fail at `make native ....`. I get a message that say `make: *** no rule to make target 'native'. Stop.` I'm guessing it's because of a missing makefile? 

If I checkout the 3.32.6 version i can see the makefile in the project. 

Is there some steps to get the makefile with the latest v8?

**Comment by noogen** [comment]
I updated instruction here: https://github.com/phpv8/v8js/issues/380#issuecomment-494561788
