### ISSUE TITLE
print() function throw exception with newline character

### ISSUE THREAD

**Issue by juan-morales** [phpv8/v8js#411]
The following piece of code throws an exception:

```
<?php

$v8 = new V8Js('PHP');

$code = <<<EOT
print("\n");
EOT;

$v8->executeString($code);

```

Output:
```
php -f testv8.php 

PHP Fatal error:  Uncaught V8JsScriptException: V8Js::compileString():1: SyntaxError: Invalid or unexpected token in /home/user/testv8.php:9
Stack trace:
#0 /home/user/testv8.php(9): V8Js->executeString('print("\n");')
#1 {main}
  thrown in /home/user/testv8.php on line 9

Fatal error: Uncaught V8JsScriptException: V8Js::compileString():1: SyntaxError: Invalid or unexpected token in /home/user/testv8.php on line 9

V8JsScriptException: V8Js::compileString():1: SyntaxError: Invalid or unexpected token in /home/user/testv8.php on line 9
```

It is the 
```
print("\n");
```

Line that is generating the error

**Comment by stesie** [comment]
I'm afraid to tell, but after all this is not php-v8js' fault :-)

What happens is that *PHP* interprets the `\n`, so your variable `$code` contains a linebreak.  And "classic" JavaScript strings may not contain linebreaks.  Try creating a `.js` file and put a linebreak in a string, and both your browser or node.js will bail out

**Comment by juan-morales** [comment]
thanks for your reply. I will try out on tuesday when I come home again. Until then

**Comment by dahousecat** [comment]
So is there anyway to create a line break with JS from within V8Js?

**Comment by stesie** [comment]
@dahousecat sure, you just need to add a second backslash (i.e. escape the backslash itself)
