### ISSUE TITLE
Can't install v8js on macOS Mojave

### ISSUE THREAD

**Issue by Jiri-Mihal** [phpv8/v8js#412]
Hello,

I can't install v8js. I've tried PECL and compilation from source. Both attempts end with some error. My setup is:

➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

➜  ~ php -v
PHP 7.3.6 (cli) (built: May 31 2019 23:38:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies

➜  ~ pecl version
PEAR Version: 1.10.9
PHP Version: 7.3.6
Zend Engine Version: 3.3.6
Running on: Darwin Jiris-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

PECL attempt:

➜  ~ pecl install v8js
downloading v8js-2.1.0.tgz ...
Starting to download v8js-2.1.0.tgz (101,553 bytes)
.......................done: 101,553 bytes
28 source files, building
running: phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
Please provide the installation prefix of libv8 [autodetect] : 
building in /private/tmp/pear/install/pear-build-jirimihalbkDWRR/v8js-2.1.0
running: /private/tmp/pear/install/v8js/configure --with-php-config=/usr/local/opt/php/bin/php-config --with-v8js
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.6.0
checking host system type... x86_64-apple-darwin18.6.0
checking target system type... x86_64-apple-darwin18.6.0
checking for PHP prefix... /usr/local/Cellar/php/7.3.6
checking for PHP includes... -I/usr/local/Cellar/php/7.3.6/include/php -I/usr/local/Cellar/php/7.3.6/include/php/main -I/usr/local/Cellar/php/7.3.6/include/php/TSRM -I/usr/local/Cellar/php/7.3.6/include/php/Zend -I/usr/local/Cellar/php/7.3.6/include/php/ext -I/usr/local/Cellar/php/7.3.6/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php/7.3.6/pecl/20180731
checking for PHP installed headers prefix... /usr/local/Cellar/php/7.3.6/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking for V8 Javascript Engine... yes, shared
checking for V8 files in default path... not found
configure: error: Please reinstall the v8 distribution
ERROR: `/private/tmp/pear/install/v8js/configure --with-php-config=/usr/local/opt/php/bin/php-config --with-v8js' failed

Compilation from source attempt:

➜  v8 git:(f8ec0ac5a1) make native library=shared -j8
make: *** No rule to make target `native'.  Stop.

I've also tried this [installation procedure](https://github.com/phpv8/v8js/issues/380#issuecomment-494561788), but without success.

Any idea? Thanks.

**Comment by Jiri-Mihal** [comment]
I've tried almost everything. Copy files here and there. Install v8 with brew. Install v8 and v8js from source (I always receive some kind of error). Really frustrating.

**Comment by Jiri-Mihal** [comment]
https://github.com/phpv8/php-v8#os-x-homebrew
https://github.com/phpv8/php-v8#building-php-v8-from-sources

Instructions above also don't work on macOS Mojave. Is there someone who installed successfully v8js on macOS Mojave with php7.3?

Unfortunately this repo is full of outdated and non-working instructions.

Standard way should be (but now it doesn't work):
➜ brew install v8
➜ pecl install v8js

**Comment by Jiri-Mihal** [comment]
I tried installation on clear macOS Sierra -> same errors.

Main issues:
1. "Standard" way doesn't work for me: `brew install v8` (works), but `sudo pecl install v8js` (doesn't)
2. I can't successfully build v8 from source. Instructions here are out dated. Official instructions are here: https://v8.dev/docs/build
3. I can't successfully build v8js from source. `make` command ends with error.

**Comment by pinepain** [comment]
Hi, sorry to hear that you are struggling with it. Please note, that php-v8 and v8js are both extension, but different one. While php-v8 may list some guides how to install v8 itself (aka libv8), those docs may be outdated due to fast-changing nature of v8 itself, sorry about it too (PRs are welcomed, as always). 

In order to get v8js you would need v8 engine itself and it is a place where you may suffer the most, at least it wasn't seamless for me. I recall that I had some issues with official v8 homebrew formula, so I stick to my own version during my experiments with v8 and php https://github.com/phpv8/homebrew-tap/blob/master/Formula/v8%406.8.rb. These days official v8 homebrew formula may have v8 version that may not simply work for v8js, worth to check what's been installed and how v8js check for `V8 files in default path`.

**Comment by noogen** [comment]
@Jiri-Mihal answered your question in #380  - basically, like @pinepain  stated above, php/v8js is not yet compatible with latest v8 (7.5.288.22) from brew, you must install previous version v8 7.4.288.25

**Comment by Jiri-Mihal** [comment]
@pinepain @noogen Thank you both for your support. With your help I successfully installed it. For anyone else who struggles with it, here step-by-step guide: https://github.com/phpv8/v8js/issues/380#issuecomment-502695765
