### ISSUE TITLE
Excuse me, how to solve the compilation error

### ISSUE THREAD

**Issue by reaink** [phpv8/v8js#420]
Linux ubuntu

PHP 5.4.20

V8js-0.1.3
Make back
```
Makefile:181: recipe for target 'v8js.lo' failed
Make: *** [v8js.lo] Error 1
```
How to solve this error

**Comment by stesie** [comment]
you need to provide more of the build output.

Please also tell which version of V8 you're using, since php-v8js 0.1.3 doesn't support recent V8 versions.

And you probably shouldn't be using both PHP 5.4 and outdated version of V8 for security reasons
