### ISSUE TITLE
Build error due to V8 API BoolValue() removed

### ISSUE THREAD

**Issue by kervinpierre** [phpv8/v8js#425]
Just in case anyone spends a bunch of time debugging.  for this error

`/tmp/v8jstmp/v8js/v8js_convert.cc:215:59: error: no matching function for call to ‘v8::Value::BooleanValue(v8::Local<v8::Context>&)’
   v8::Maybe<bool> value = jsValue->BooleanValue(v8_context);
`

Compiling against a very recent version of V8 will fail due to this patch: https://github.com/v8/v8/commit/c76f377a990343b18953123c2726337b38c59812#diff-3dd7a0f46b1e5c1cc67921449e7180ac

Looks like it "may" have gone into 7.6.58

**Comment by kervinpierre** [comment]
Also, looks like GCC build is broken until 7.7.47 due to: https://github.com/v8/v8/commit/3b8c624bda58d05aea80dd9626cd550537d6ac3f#diff-1dd7b6eaeebb8457fcb57aa637f469dc

**Comment by SinisaG** [comment]
@kervinpierre : Thank you for the hint! Was looking at what's causing this. Using version `7.6.57` it compiles as expected. :ok_hand:  Of course I would be :open_mouth: if the latest `master` would just work. ;)

**Comment by redbullmarky** [comment]
fixed with #435
