### ISSUE TITLE
Fix outdated documentation of how to install libv8?

### ISSUE THREAD

**Issue by TysonAndre** [phpv8/v8js#428]
In README.md

> If you execute untrusted JavaScript code, make sure to use V8 version 6.4.388.18, 6.5.143 or higher. See notes on untrusted code mitigations for further details.

However, the latest version of v8js requires libv8 version 6.9, so this note should mention it only needs to be checked when building older releases of v8js (or be removed)

**Comment by itksb** [comment]
It took me a couple of days to figure out how to build a docker image with this library. Hope [this link](https://github.com/itksb/php-fpm-v8js-docker) helps, see Dockerfile
