### ISSUE TITLE
Segmentation fault with libv8 8.0

### ISSUE THREAD

**Issue by joehoyle** [phpv8/v8js#439]
When building v8js and against libv8 version 8.0 (specifically), things compile fine, but I get a segfault when trying to run anything that touches the v8js bridge. For example:

```
php -r '$v8js = new V8Js(); $v8js->executeString("var_dump()");'
Segmentation fault
```

I don't have all the debugging symbols etc set up, but if I run it with gdb, here is what I see:

```
/usr/src/app # gdb -ex=r --args php -r '$v8js = new V8Js(); $v8js->executeString("var_dump()");'
Reading symbols from php...
(No debugging symbols found in php)
Starting program: /usr/local/bin/php -r \$v8js\ =\ new\ V8Js\(\)\;\ \$v8js-\>executeString\(\"var_dump\(\)\"\)\;
warning: Error disabling address space randomization: Operation not permitted
[New LWP 23]

Thread 1 "php" received signal SIGSEGV, Segmentation fault.
0x00007f41cb15c0d7 in v8js_to_zval (jsValue=jsValue@entry=..., return_value=0x7fff7b560540, flags=flags@entry=1, isolate=0x2c8200000000) at /usr/local/v8/include/v8-internal.h:315
315	    return ReadRawField<internal::Address>(heap_object_ptr, offset);
```

**Comment by raul-dan** [comment]
I'm getting segmentation fault as well:

```text
root@f79df1ba579f:/var/www/html# php --ri v8js   

v8js

V8 Javascript Engine => enabled
V8 Engine Compiled Version => 8.4.0
V8 Engine Linked Version => 8.4.0 (candidate)
Version => 2.1.1

Directive => Local Value => Master Value
v8js.flags => no value => no value
v8js.icudtl_dat_path => no value => no value
v8js.use_date => 0 => 0
v8js.use_array_access => 0 => 0


root@f79df1ba579f:/var/www/html# php --version
PHP 7.4.1 (cli) (built: Dec 28 2019 20:56:41) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
root@f79df1ba579f:/var/www/html# 

```

**Comment by wmjasonward** [comment]
@joehoyle @lrauldan Did you enable pointer compression when you built v8js? Or, alternatively, did you disable it when building v8? Starting with v8 version 8.0 [pointer compression is enabled by default](https://docs.google.com/document/d/10qh2-b4C5OtSg-xLwyZpEI5ZihVBPtn1xwKBbQC26yI/edit). However, pointer compression is not enabled by default when building v8js. The mismatch can cause a seg fault, but you should have seen all failures when you run `make test` if that was the problem.

To disable pointer compression when building v8:
`tools/dev/v8gen.py -vv x64.release -- is_component_build=true use_custom_libcxx=false v8_enable_pointer_compression=false`

or, to enable pointer compression when building v8js:
`./configure --with-v8js=/opt/v8 LDFLAGS="-lstdc++" CPPFLAGS="-DV8_COMPRESS_POINTERS"`

Those commands are for linux, I haven't built on mac or windows so adjust as necessary.

**Comment by joehoyle** [comment]
@wmjasonward ah interesting, I definitely didn't change any defaults when building libv8. I'll give that a go.

**Comment by raul-dan** [comment]
Once I enabled pointer compression the tests successfully passed and I do not get segmentation fault anymore. Thank you Jason!

**Comment by forrestmid** [comment]
The following fixes the issue for MacOS:

`./configure CXXFLAGS="-Wno-c++11-narrowing" CPPFLAGS="-DV8_COMPRESS_POINTERS"`
