### ISSUE TITLE
V8Js works with node module?

### ISSUE THREAD

**Issue by grandemestre** [phpv8/v8js#447]
I have this code to render a javascript code with PHP and V8JS but it doesn't work. Does anyone know where the problem is?

```
<?php

$v8 = new V8Js();
$code = file_get_contents('index2.js');
$result = $v8->executeString( $code );
var_dump($result);
?>
```
index2.js

```
const jsdom = require('jsdom');
const { JSDOM } = jsdom;

const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
console.log(dom.window.document.querySelector("p").textContent); // "Hello world"
```
The error that occurs:
```
Fatal error: Uncaught V8JsScriptException: V8Js::compileString():1: No module loader in index.php on line 6
```
I imagine the problem is in the require of the node module jsdom

**Comment by redbullmarky** [comment]
You need  ‘$v8->setModuleLoader’ with a callback that resolves the code of ‘jsdom’ from your require statement.

**Comment by grandemestre** [comment]
> You need ‘$v8->setModuleLoader’ with a callback that resolves the code of ‘jsdom’ from your require statement.

I don't know if I did it right. I tried this:
```
<?php
$v8 = new V8Js();
$code = file_get_contents('index2.js');
$v8->setModuleLoader(function($module) {

    switch ($module) {
      case 'jsdom':
        return 'require("jsdom");';
  
      default:
        return 'print(' . json_encode($module . PHP_EOL) . ');';
    }
  });
$result = $v8->executeString( $code );

var_dump($result);
?>
```
Now I have this return error:
`Fatal error: Uncaught V8JsScriptException: jsdom:1: Module cyclic dependency in index.php on line 14`

**Comment by chrisbckr** [comment]
Maybe this can help you:
https://gist.github.com/stesie/c9143b98355295420470

**Comment by grandemestre** [comment]
> Maybe this can help you:
> https://gist.github.com/stesie/c9143b98355295420470

I tried but it has no documentation. I couldn't make it work

**Comment by redbullmarky** [comment]
@grandemestre Not quite. The return value of the module loader should be the full contents of the JS file you’re trying to ‘require’

**Comment by stesie** [comment]
@grandemestre one key point to stress here, php-v8js itself does *not* provide node-style module loading by itself. It provides a commonjs-style facility that you can use to provide that however.  This is php-v8js will never access local files and provide these to the javascript engine itself (after all its the whole point of the project to keep those separated).
So the point of module loader/normaliser is to bridge this gap, i.e. read the files and provide their contents from php (with access control etc. as needed for your usecase). That is the "module loader" like does some kind of file_get_contents and returns the javascript string. The "normaliser"'s job is to provide meaningful names to the loader on recursive require calls from javascript side

Regarding the Gist I've posted like years ago?  What kind of documentation are you missing?  It has an example that outlines how the loading can be achieved.

**Comment by chrisbckr** [comment]
@grandemestre its not a node's 100% compatible module loader implementation.
Probably you will need do adapt to your needs and change something here and there, but will work.
I've tested some time ago. Again... it's not 100% but it is a start to understand and implement your own module loader.

**Comment by grandemestre** [comment]
I can make it work with a moment module for example but it doesn't work with jsdom. Is it possible to make this work with jsdom? I don't know what else to try.
```
<?php

$v8 = new V8Js();

require_once __DIR__.'/V8JsNodeModuleLoader.php';
require_once __DIR__.'/V8JsNodeModuleLoader_NativeFileAccess.php';

$fai = new V8JsNodeModuleLoader_NativeFileAccess();
$loader = new V8JsNodeModuleLoader($fai);

$loader->addOverride('fs', 'Hacks/fs');
$loader->addOverride('vm', 'Hacks/vm');
$loader->addOverride('path', 'Hacks/path');

$v8->setModuleNormaliser([ $loader, 'normaliseIdentifier' ]);
$v8->setModuleLoader([ $loader, 'loadModule' ]);

try {
    
    $code = file_get_contents('index2.js');
    $v8->executeString($code);
}
catch (V8JsScriptException $e) {
    var_dump($e);
}

?>
```
**ERROR LOG**
[https://imgur.com/QJfVfma](https://imgur.com/QJfVfma)

**Comment by stesie** [comment]
@grandemestre well, the trace says what's wrong: `Module not found: url`.

And I'd suppose there's no module in `node_modules/url` and also there's no matching `addOverride` call. After all `url` is a node-native module, which you're missing here. This is you'll need to provide some kind of shim for it, either roll your own or copy one of the existing ones and provide that.

Anyways I think you'll be better of with using something like browserify, that auto-provides shims (e.g. for "url"), and load the result into php-v8js. But YMMV

**Comment by linfuwan12** [comment]
@grandemestre 
Hello, I would like to ask if you have successfully made PHPV8 run Nodejs. I also have similar requirements now, but according to the example operation, it did not run successfully

**Comment by grandemestre** [comment]
> @grandemestre
> Hello, I would like to ask if you have successfully made PHPV8 run Nodejs. I also have similar requirements now, but according to the example operation, it did not run successfully

Hello, I couldn't. I managed to run some other modules but not jsdom. I am going back to work to try to find the solution.

**Comment by grandemestre** [comment]
> @grandemestre well, the trace says what's wrong: `Module not found: url`.
> 
> And I'd suppose there's no module in `node_modules/url` and also there's no matching `addOverride` call. After all `url` is a node-native module, which you're missing here. This is you'll need to provide some kind of shim for it, either roll your own or copy one of the existing ones and provide that.
> 
> Anyways I think you'll be better of with using something like browserify, that auto-provides shims (e.g. for "url"), and load the result into php-v8js. But YMMV

I had given up but recently I started playing again and managed to solve using $ loader-> addOverride ('url', 'Hacks / url'); I don't know if it was the right way but the error is gone.

The problem is that there was an error in loading modules that jsdom is dependent on. Have you managed to make this library work with jsdom? Do you have an example of how the code looks?

**Comment by linfuwan12** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I think before is used to decrypt the crypto - js, is no longer use v8js, if you're going to crawl web pages,https://simplehtmldom.sourceforge.io/ can use similar examples of PHP/js
            
        
    
    
        //crypto-js.js!function () {    this.Crypto = {        decode: function f(u, p) {            return CryptoJS(u, p);        }    };    function CryptoJS(u, p) {        return u+p;    }}//php$script = file_get_contents("./crypto-js.js");$snapshot = V8Js::createSnapshot($script);$v8 = new V8Js('PHP', array(), array(), true, $snapshot);$result = $v8->executeString("this.Crypto.decode(u,p)");
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                a18169627069
                            
                    
                        
                            
                                    a18169627069@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 10/31/2020 01:58，grandemestre<notifications@github.com> wrote： 




@grandemestre well, the trace says what's wrong: Module not found: url.
And I'd suppose there's no module in node_modules/url and also there's no matching addOverride call. After all url is a node-native module, which you're missing here. This is you'll need to provide some kind of shim for it, either roll your own or copy one of the existing ones and provide that.
Anyways I think you'll be better of with using something like browserify, that auto-provides shims (e.g. for "url"), and load the result into php-v8js. But YMMV

I had given up but recently I started playing again and managed to solve using $ loader-> addOverride ('url', 'Hacks / url'); I don't know if it was the right way but the error is gone.
The problem is that there was an error in loading modules that jsdom is dependent on. Have you managed to make this library work with jsdom? Do you have an example of how the code looks?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
