### ISSUE TITLE
Uncatchable?  Fatal V8 error in invalid array length: Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by bjorno43** [phpv8/v8js#448]
**General Info**<br/>
I'm working on a Discord bot using DiscordPHP and V8JS. The idea is to make something similar to Codewars. The bot gives a challenge within the room and users can provide Javascript solutions to solve the challenge.

**The Problem**<br/>
The downside of the nature of this app is that users can input any kind of JS code they want. Hence V8JS to properly sandbox this. The problem is that V8JS crashes with the following JS code:

```javascript
const crash = Array(200000000).fill("ha");
crash;
```

Despite setting up proper exception handlers:

```php
try {
	$v8 = new V8Js();
	$v8->setTimeLimit(10000);
	$v8->setMemoryLimit(1024000);
	$output = $v8->executeString($js);
} catch (V8JsTimeLimitException $e) {
	// Not important
} catch (V8JsMemoryLimitException $e) {
	// Not important
} catch (V8JsException $e) {
	// Not important
} catch (Exception $e) {
	// Not important
}
```

**Crash Log**

> <--- Last few GCs --->

```
[1324:0000021564E397F0]     1143 ms: Scavenge 256.7 (290.2) -> 256.7 (290.2) MB, 53.0 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure
[1324:0000021564E397F0]     2289 ms: Scavenge 512.7 (546.2) -> 512.7 (546.2) MB, 102.0 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure
[1324:0000021564E397F0]     5033 ms: Mark-sweep 1024.7 (1058.2) -> 1024.7 (1058.2) MB, 628.0 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure scavenge might not succeed
```

> <--- JS stacktrace --->
```
Security context: 0x0375810997d9 <JSObject>
0: builtin exit frame: fill(this=0x028bb1f00181 <JSArray[200000000]>,0x03758109ce59 <String[#2]: ha>,0x028bb1f00181 <JSArray[200000000]>)
1: /* anonymous */ [000003758109CFE9] [V8Js::compileString():1] [bytecode=000003758109CF41 offset=46](this=0x028bb1f001a1 <JSGlobal Object>)
2: InternalFrame [pc: 00007FFF803A29E1]
3: EntryFrame [pc: 00007FFF803A25CC]
```

==== Details ===========...

Warning: Fatal V8 error in invalid array length: Allocation failed - JavaScript heap out of memory in ....

```
#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
#
#
#FailureMessage Object: 000000BA03FF6B98
==== C stack trace ===============================

        v8::base::debug::StackTrace::StackTrace [0x00007FFFBEF1F66B+27]
        v8::platform::DefaultPlatform::GetStackTracePrinter [0x00007FFFC04137A8+56]
        V8_Fatal [0x00007FFFBEF17AB7+215]
        v8::internal::FatalProcessOutOfMemory [0x00007FFF7F9A04AB+715]
        v8::internal::Heap::CreateFillerObjectAt [0x00007FFF7FE0D0E3+10531]
        v8::internal::Factory::NewFixedArrayWithFiller [0x00007FFF7FDE20EA+74]
        v8::internal::Factory::NewUninitializedFixedArray [0x00007FFF7FDE2DAE+46]
        v8::internal::EhFrameIterator::DecodeSLeb128 [0x00007FFF7FD802E9+97385]
        v8::internal::EhFrameIterator::DecodeSLeb128 [0x00007FFF7FD80A84+99332]
        v8::internal::JSReceiver::GetContextForMicrotask [0x00007FFF7FFDD533+63747]
        v8::internal::HashTable<v8::internal::SimpleNumberDictionary,v8::internal::SimpleNumberDictionaryShape>::Rehash [0x00007FFF7FF70040+7664]
        v8::internal::HashTable<v8::internal::SimpleNumberDictionary,v8::internal::SimpleNumberDictionaryShape>::Rehash [0x00007FFF7FF6F08E+3646]
        v8::internal::operator<< [0x00007FFF7FA4BE7A+150154]
        v8::internal::operator<< [0x00007FFF7FA4B7C6+148438]
        v8::internal::NativesCollection<0>::GetScriptsSource [0x00007FFF8043BB66+660486]
```

**Comment by redbullmarky** [comment]
Just for sanity, catching ‘Throwable’ rather than ‘Exception’ often leaves less to slip through the net. Might help here, might not, but worth the swap anyway.

**Comment by bjorno43** [comment]
> 
> 
> Just for sanity, catching ‘Throwable’ rather than ‘Exception’ often leaves less to slip through the net. Might help here, might not, but worth the swap anyway.

Thanks, I did try that, but unfortunately 'Throwable' doesn't catch this problem either. I think it's V8JS crashing before anything at all is returned to PHP. So ye, obviously PHP can't catch it.

**Comment by kynx** [comment]
OOMs in PHP aren’t really catchable - look, the engine has run out of memory; what’s it supposed to do, allocate more for the exception message? 

> properly sandbox

How comfortable are you with this assumption? I only lurk here - a few years ago I had the need, then it went away. It’s a very cool project. But back then I was only thinking trusted code....

Maybe dig into how https://jsfiddle.net/ do things behind the scenes. Your quest requires paranoia 😬

**Comment by bjorno43** [comment]
@kynx Well perhaps my understanding behind `setMemoryLimit()` and its exception `V8JsMemoryLimitException` is flawed, but it seems to me it's supposed to exactly prevent this kind of problem?

And ye, I know this requires a paranoid approach, haha. But security is something I can deal with. The engine crashing on "valid" JS code unfortunately is not. It'll be impossible to analyze any valid input for possible memory issues before throwing it against the engine. Unless you do it manually, but that takes away the purpose of the entire app.

And jsfiddle (or any of those sites) simply rely on the user's browser to run the code. The code is basically just pushed inside an iframe. If someone creates "bad code", it'll just crash their own browser, nothing else.

**Comment by stesie** [comment]
both `setMemoryLimit`  and `setTimeLimit` are like to *not* do exactly what you suppose they would do. This is due to V8 not actively allowing to limit time and memory usage. Instead they spin up a watcher thread that checks memory consumption every 10ms and stop execution if isolate's heap size exceeds that given limit.

Yet if you directly trigger the heap size limit in one go (like you do with the massive array allocation) it will (likely) come to late.

And yes, V8 just (yet properly) terminates the execution in this case and this extension cannot/doesn't do much against that. Hence you cannot currently catch this from PHP userland.

PS: if you want to enforce strong heap size limits on the engine, you likely don't want to use `setMemoryLimit` but reconfigure the engine's heap via ini_set/v8js.flags -- yet still this triggers a engine shutdown and not just throws or so

**Comment by bjorno43** [comment]
@stesie That makes a lot of sense. Thanks for the explanation. Would it perhaps be possible to at least keep the PHP script running? I understand that the engine crashes, but the only other "workaround" I can think of is to use Supervisor or something like that and have it automatically execute the PHP script again upon a crash. This wouldn't allow me to send any form of feedback to the user about what happened, so I'd rather not use that solution for this problem.

PS: If this problem can't be solved due to PHP limitations, I see no reason to keep this issue open. So after your reply, feel free to close it (or I'll do it myself after I've seen it).

**Comment by stesie** [comment]
Well, yes and no.  First of all, V8 allows to register a "fatal error handler", ... which is provided by the php-v8js extension.  Search for `v8js_fatal_error_handler` in `v8js_class.cc` file. This error handler currently just calls `zend_error` with E_WARNING, which triggers the PHP warning you've been noticing. As soon as the error handler returns to V8, V8 stops the process.

This is, if we'd change this extension to allow registering a PHP callback "fatal error handler" and you'd block execution just there, then you'd a) be able to signal your user what has just happend  and b) postpone process termination as long as you want to (of course with V8 still being around, but not functioning any longer)

This might already be possible (haven't tried it out) by providing a php error handler with `\set_error_handler`, yet ugly for obvious reasons...

**Comment by bjorno43** [comment]
@stesie Thanks a lot! I think I can work with that. 🙂 I'll close the issue now.
