### ISSUE TITLE
Error: Package exports for 'colorette' do not define a valid

### ISSUE THREAD

**Issue by KitaXvost** [phpv8/v8js#452]
**at require (v8-compile-cache/v8-compile-cache.js:161:20) {
code: 'MODULE_NOT_FOUND'**

The module `v8-compile-cache` is present in the `node_modules` folder and reinstall the package also did not help.

This problem appeared on the server after installation `PHP-V8.JS`

If you use `node_modules`, which was created before `v8` and which also contains `v8-compile-cache`, the project calmly executes `npm run dev`, and if you start `npm i` again or add some other package like: `npm i bootstrap-vue-the` installation goes fine, and compilation is interrupted with the same error.

Can you tell me if there is a way to fix this?

**Comment by redbullmarky** [comment]
this one's not related to V8Js; try https://www.npmjs.com/package/v8-compile-cache
