### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by ghost** [phpv8/v8js#453]
I've followed multiple guides, none of them worked. I'm using ubuntu 20.04 and php 7.3. The last guide I followed was this https://github.com/phpv8/v8js/blob/php7/README.Linux.md and when  I try to run ./configure --with-v8js=/opt/v8 LDFLAGS="-lstdc++" CPPFLAGS="-DV8_COMPRESS_POINTERS" I get this error http://prntscr.com/uve082

**Comment by bpanatta** [comment]
Did you do the "optional" steps from the guide?
`git checkout 8.0.426.30`
`gclient sync`

This solved this specific problem for me. However I got stuck with a failed `make test`.

Using PHP 7.4.3 here

**Comment by keanpogi** [comment]
> Did you do the "optional" steps from the guide?
> `git checkout 8.0.426.30`
> `gclient sync`
> 
> This solved this specific problem for me. However I got stuck with a failed `make test`.
> 
> Using PHP 7.4.3 here

I am still facing the same issues currently, says there is a problem with PHP.
