### ISSUE TITLE
Getting error while running make command  on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by anilkoeri** [phpv8/v8js#455]
Please help me, trying to build on macOs but geting below issue

    brew install v8

    $ git clone https://github.com/phpv8/v8js

    $ cd v8js
    $ phpize
    $ ./configure CXXFLAGS="-Wno-c++11-narrowing" --with-v8js="/usr/local/Cellar/v8/8.6.395.17/libexec" --with-php-config="/Applications/MAMP/bin/php/php7.4.9/bin/php-config"
    $ make
    $ make test
    $ make install

anilkoeri@Anils-MacBook v8js % make
/bin/sh /Users/anilkoeri/v8js/libtool --mode=compile g++ -Wno-c++11-narrowing -std=c++11 -I. -I/Users/anilkoeri/v8js -DPHP_ATOM_INC -I/Users/anilkoeri/v8js/include -I/Users/anilkoeri/v8js/main -I/Users/anilkoeri/v8js -I/Applications/MAMP/bin/php/php7.4.9/include/php -I/Applications/MAMP/bin/php/php7.4.9/include/php/main -I/Applications/MAMP/bin/php/php7.4.9/include/php/TSRM -I/Applications/MAMP/bin/php/php7.4.9/include/php/Zend -I/Applications/MAMP/bin/php/php7.4.9/include/php/ext -I/Applications/MAMP/bin/php/php7.4.9/include/php/ext/date/lib -I/usr/local/Cellar/v8/8.6.395.17/libexec/include -I/usr/local/Cellar/v8/8.6.395.17/libexec  -DHAVE_CONFIG_H  -Wno-c++11-narrowing   -c /Users/anilkoeri/v8js/v8js_array_access.cc -o v8js_array_access.lo 
mkdir .libs
 g++ -Wno-c++11-narrowing -std=c++11 -I. -I/Users/anilkoeri/v8js -DPHP_ATOM_INC -I/Users/anilkoeri/v8js/include -I/Users/anilkoeri/v8js/main -I/Users/anilkoeri/v8js -I/Applications/MAMP/bin/php/php7.4.9/include/php -I/Applications/MAMP/bin/php/php7.4.9/include/php/main -I/Applications/MAMP/bin/php/php7.4.9/include/php/TSRM -I/Applications/MAMP/bin/php/php7.4.9/include/php/Zend -I/Applications/MAMP/bin/php/php7.4.9/include/php/ext -I/Applications/MAMP/bin/php/php7.4.9/include/php/ext/date/lib -I/usr/local/Cellar/v8/8.6.395.17/libexec/include -I/usr/local/Cellar/v8/8.6.395.17/libexec -DHAVE_CONFIG_H -Wno-c++11-narrowing -c /Users/anilkoeri/v8js/v8js_array_access.cc  -fno-common -DPIC -o .libs/v8js_array_access.o
In file included from /Users/anilkoeri/v8js/v8js_array_access.cc:17:
.**/php_v8js_macros.h:35:10: fatal error: 'php_config.h' file not found
#include "php_config.h"
         ^~~~~~~~~~~~~~**
1 error generated.
make: *** [v8js_array_access.lo] Error 1

**Comment by anilkoeri** [comment]
I was able to fix the issue by removing "#include "php_config.h" in file php_v8js_macros.h.

**Comment by noogen** [comment]
See my response here: https://github.com/phpv8/v8js/issues/457#issuecomment-736812801
