### ISSUE TITLE
checking for V8 files in default path... not found

### ISSUE THREAD

**Issue by romxuk** [phpv8/v8js#461]
checking for V8 Javascript Engine... yes, shared
checking for V8 files in default path... not found
configure: error: Please reinstall the v8 distribution

I am running centos 7, how do I fix this error?

**Comment by celestora** [comment]
Is your system 64 bit? If so, could you try to use `--with-libdir=lib64` with configure?

**Comment by rtlprmft** [comment]
If compiling under Ubuntu 20.04 using the nodejs-dev package (containing v8 6.8) the default paths are /usr/include/v8 and /lib/x86_64-linux-gnu for the headers and libaries. As whatever I tried configure assumes to find them in /some-path/include and /some-path/lib there is no way to compile it without patching configure. It would be good to have an overwrite --with-v8js-include and --with-v8js-lib. Even better would be to include automatic detection for these default paths.
