### ISSUE TITLE
Compilation problems with v8 6.8

### ISSUE THREAD

**Issue by rtlprmft** [phpv8/v8js#464]
During compilation, I get a lot of issues because BooleanValue takes isolate as an argument instead of v8_context and once replaced, it returns a Maybey<Bool> rather than a bool that first have to be checked for contents. I also had to fix some other minor issues.

This happens with the nodejs-dev package on Ubunu 20.04 which contains v8 6.8.

After my fixes, still some tests fail (see attachment), most of them because they return int(0) and int(1) rather than bool(false) and bool(true)

executeString() and register*() seg fault. I am not sure whether this is related. For all other tests, I checked that it is the previously mentioned issue.

I attach the full report
[php_test_results_20210322_1102.txt](https://github.com/phpv8/v8js/files/6188316/php_test_results_20210322_1102.txt)

I also attach a diff with the required changes to make it compile.
[v8js.txt](https://github.com/phpv8/v8js/files/6188342/v8js.txt)

**Comment by redbullmarky** [comment]
Closing this one as #486 bumps the minimum V8 version to 9+
