### ISSUE TITLE
Error when make test and build

### ISSUE THREAD

**Issue by popcornrus** [phpv8/v8js#466]
Error while trying to compile with the make command

Log when I compile library:
https://pastebin.com/uHKQ5CNV

PHP: v8.0.3
Apache2: Apache/2.4.41 (Ubuntu)

**Comment by mohamedale** [comment]
Your issue like [my issue](https://github.com/phpv8/v8js/issues/468), did you solve that?

**Comment by tmotyl** [comment]
see https://github.com/phpv8/v8js/issues/458 for php8 support

**Comment by mohamedale** [comment]
> see #458 for php8 support

thanks bro, i followed this [tree](https://github.com/nvq247/v8js/tree/php8.0) but some tests failed but i tried to run [this code](https://github.com/phpv8/v8js/issues/458#issuecomment-749149693) and it works at the end.
