### ISSUE TITLE
cannot install on mac

### ISSUE THREAD

**Issue by donakhseputa** [phpv8/v8js#467]
what im done:
- run `brew install v8`
- run `sudo /Applications/MAMP/bin/php/php7.4.1/bin/pecl install v8js`
error found:
`ERROR: /private/tmp/pear/temp/v8js/configure --with-php-config=/Applications/MAMP/bin/php/php7.4.1/bin/php-config --with-v8js' failed`
i have tried run `sudo /Applications/MAMP/bin/php/php7.4.1/bin/pecl install v8js-beta` too. but same result.

any solution?

**Comment by nullwriter** [comment]
@donny26utama If you're stuck, I would instead install using docker, it makes things easier
