### ISSUE TITLE
TypeError: Illegal invocation on require

### ISSUE THREAD

**Issue by Stubbsware** [phpv8/v8js#476]
When calling a function with require I am getting an error of TypeError: Illegal invocation, when assigning specific functions to a constant.

I have set v8js up with

```
$v8 = new V8Js('app')
$v8->setModuleLoader(function($module) use ($v8) {
            $loader = "Core\Requires\\" . strtolower($module)
            
            if ( class_exists($loader)) {
                return new $loader
            } else {
                throw new \V8JsException("Unknown require `$module`.")
            }
})
$v8->executeString(file_get_contents($filename), $filename, V8Js::FLAG_PROPAGATE_PHP_EXCEPTIONS);
```
And I've created the required functions as follows

```
<?php

namespace Core\Requires;

class tstRequire {
    public function doSomething($param) {
        return $param;
    }
}
```

If I run the JS script as follows, everything works

```
const tstRequire = require('tstRequire')

tstRequire.doSomething("Doing This")
```

This will return Doing This to the output. However, if I try the following, it crashes with TypeError: Illegal invocation

```
const { doSomething } = require('tstRequire')

doSomething("Doing This")
```

If i var_dump doSomething, it is showing object(Closure)#549176 { function () { [native code] } } - So the code is their, just just not executing.

**Comment by redbullmarky** [comment]
‘setModuleLoader’ should return a string which is a JS script, rather than a PHP object/function.

**Comment by Stubbsware** [comment]
I don't know the inner workings of v8js. All I do know is the bug I found above.

const variable = require('moduleloader) // Works

const { function } = require('moduleloader) // Does not work, fails with TypeError: Illegal invocation


If you set the moduleloader to execute a JS script, with the functions exported (instead of calling a PHP namespace/class etc then both the commands above work fine.

**Comment by redbullmarky** [comment]
But your latter point (where you say it works) is how I’d expect it to work. The callback for setModuleLoader needs to respond with the actual JS (string), not a PHP class/function or whatever.

**Comment by Stubbsware** [comment]
Sorry, I think their is some misunderstanding. The setModuleLoader, as per the documents states "Provide a function or method to be used to load required modules. **This can be any valid PHP callable**." Regardless of calling JS code, **my latter point** -  which is not what I need to do, but also does work should someone do it.

v8JS example : https://github.com/phpv8/v8js/blob/php7/tests/commonjs_native_basic.phpt

My bug report is:

As I mentioned in my original post, Calling PHP callable code is working, but only if I require the **entire class**.
`const var = require('class')`

 If you try requiring a single function from the class
`const { func } = require('class')`

This fails - This is allowed, as per the documents - So this point remains a bug.

**Comment by redbullmarky** [comment]
i see; it looks like there's a custom implementation then for native PHP objects. i guess the usage example i was thinking was more:

```php
<?php
$modcode = <<<EOF
exports.foo = {
	bar: () => {
		return "I am bar";
	},
	baz: () => {
		return "Je suis baz";
	}
}

exports.hello = () => {
	return "hello, world!";
}
EOF;

$maincode = <<<EOF
const { foo, hello } = require('./foo');

print(foo.bar() + "\\n");
print(foo.baz() + "\\n");

print(hello() + "\\n\\n");

var_dump(foo);
var_dump(hello);
EOF;

$v = new V8Js();
$v->setModuleLoader(function($modulename) use ($modcode) {
	return $modcode;
});

$v->executeString($maincode);
```

where the module loader callback returns actual javascript rather than a PHP.

**Comment by stesie** [comment]
Hej :)

sorry for being around so rarely...

First of all, yes, native modules should be supported, i.e. returning PHP code from the `setModuleLoader` callable.

However there are some subtleties where PHP and JS differ, that show up here ...

If you call like this:

```
const var = require('class')
var.theMethod(42);
```

... the `theMethod` is called with `$this` set to `var` which points to the object returned from `setModuleLoader` instance.

With this call:

```
const { func } = require('class')
func(42)
```

... func is called with `$this` equal to `null`. Yet this is not a valid call. After all you invoke a class method.

I haven't tried it, yet if you'd `func.apply(validRefToYourClass, 42)` it likely should work just fine.

> This fails - This is allowed, as per the documents - So this point remains a bug.

To be honest I'm not so sure. I'd tend to agree if `func` was `static`.
