### ISSUE TITLE
Segmentation fault when exit() is called in some circustances

### ISSUE THREAD

**Issue by chrisbckr** [phpv8/v8js#497]
V8: 10.2.154.8 (tested with 10.5.29 and have the same problem)
PHP: 8.1.14
v8js: branch php8 (commit 461230be276dc423d8eebf0c9ea769c71d47b7f6)

How to replicate:
```php
<?php
class Foo {
    function __destruct() {
	echo 'Foo __destruct' . PHP_EOL;
    }

    function somecall() {
	echo 'Foo somecall' . PHP_EOL;
    }

    function bar() {
	global $v8;
	echo 'Foo bar' . PHP_EOL;
	// $v8->executeString('exit();');
	exit;
    }
}

$v8 = new \V8Js();
$v8->foo = new Foo();

$JS = <<< EOT
PHP.foo.somecall();
PHP.foo.bar();
EOT;

$v8->executeString($JS, '', \V8JS::FLAG_PROPAGATE_PHP_EXCEPTIONS);

echo 'Run ok' . PHP_EOL;
echo PHP_EOL;
```

If I run:
```
Foo somecall
Foo bar
Falha de segmentação
```

But if I run:
$v8->executeString('exit();');
just before the exit, everything runs ok.

```
Foo somecall
Foo bar
Foo __destruct
```

Important to notice that if I remove the flag \V8JS::FLAG_PROPAGATE_PHP_EXCEPTIONS, it will run fine too!

**Comment by chrisbckr** [comment]
After 24h+ searching I think I found the solution.

In v8js_object_export.cc on de 'failure:' I found that is need to check the exception with zend_is_unwind_exit() and zend_is_graceful_exit().

I will create a pull request with this code.

**Comment by stesie** [comment]
PR is now merged, hence I'm closing this.  Thanks for pointing this out (and debugging it)!
