### ISSUE TITLE
Divergences & pull requests

### ISSUE THREAD

**Issue by redbullmarky** [phpv8/v8js#499]
Hey!
Would it be possible to look at some of the merges that have made it into PHP7's version that might not have gone into the PHP8.x ones? e.g

https://github.com/phpv8/v8js/pull/490/commits/19111d65147f063cd27e75d09948a95fa73fe896

https://github.com/phpv8/v8js/commit/883c9000c3ed6ae293006af967dd7f2ae41b6d41

There are also a couple of pull requests that can probably be applied now, too?
Hope you're well!

Cheers.

**Comment by stesie** [comment]
yep, should really look into this.  But I'm likely busy next two weekends.  No plans for the ones after that so far, ...

**Comment by redbullmarky** [comment]
Yeah understood, I think getting things in sync will help so at least all versions have the same functionality. After that I’d like to probably get stuck in again!

**Comment by stesie** [comment]
:heavy_check_mark: PRs are merged  
:heavy_check_mark: php7 branch is merged into php8

thanks Mark for poking me :slightly_smiling_face:

**Comment by redbullmarky** [comment]
@stesie as always, thank you so much for your awesome work on the project!
