### ISSUE TITLE
Trying to compile with php8 branch on ubuntu 22, getting error: could not determine libv8 version (v8 compiled succesfully)

### ISSUE THREAD

**Issue by rzarectah88** [phpv8/v8js#500]
Hey, I've been trying to compile this for 3 days now, always getting this error. I tried with homebrew on my mac, on my laptop with ubuntu 22 and a vps running ubuntu 22. Always getting this error below. I'm able to compile v8 successfully and have all the needed files in `/opt/v8` 

I also tried with c++17 as opposed to c++14 based on suggestion from another issue, still no luck. 

`checking for g++... g++`
`checking whether the compiler supports GNU C++... yes`
`checking whether g++ accepts -g... yes`
`checking for g++ option to enable C++11 features... none needed`
`checking how to run the C++ preprocessor... g++ -E`
`checking for C standard version... c++14`
`checking how to allow c++14 narrowing... -Wno-narrowing`
`checking for libv8_libplatform... found`
`checking for V8 version... NONE`
`configure: error: could not determine libv8 version`

this is the output of the config.log, any help is appreciated

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.71.  Invocation command line was

  $ ./configure --with-v8js=/opt/v8 LDFLAGS=-lstdc++ CPPFLAGS=-DV8_COMPRESS_POINTERS

## --------- ##

hostname = moe-G7-7700
uname -m = x86_64
uname -r = 5.15.0-58-generic
uname -s = Linux
uname -v = #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /tmp/depot_tools/
PATH: /home/moe/.local/bin/
PATH: /usr/local/sbin/
PATH: /usr/local/bin/
PATH: /usr/sbin/
PATH: /usr/bin/
PATH: /sbin/
PATH: /bin/
PATH: /usr/games/
PATH: /usr/local/games/
PATH: /snap/bin/
PATH: /snap/bin/

## ----------- ##

configure:2756: looking for aux files: ltmain.sh config.guess config.sub
configure:2769:  trying ./build/
configure:2798:   ./build/ltmain.sh found
configure:2798:   ./build/config.guess found
configure:2798:   ./build/config.sub found
configure:2915: checking for grep that handles long lines and -e
configure:2979: result: /usr/bin/grep
configure:2984: checking for egrep
configure:3052: result: /usr/bin/grep -E
configure:3057: checking for a sed that does not truncate output
configure:3127: result: /usr/bin/sed
configure:3271: checking for pkg-config
configure:3294: found /usr/bin/pkg-config
configure:3306: result: /usr/bin/pkg-config
configure:3331: checking pkg-config is at least version 0.9.0
configure:3334: result: yes
configure:3410: checking for cc
configure:3431: found /usr/bin/cc
configure:3442: result: cc
configure:3473: checking for C compiler version
configure:3482: cc --version >&5
cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3493: $? = 0
configure:3482: cc -v >&5
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04) 
... rest of stderr output deleted ...
configure:3493: $? = 0
configure:3482: cc -V >&5
cc: error: unrecognized command-line option '-V'
cc: fatal error: no input files
compilation terminated.
configure:3493: $? = 1
configure:3482: cc -qversion >&5
cc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
cc: fatal error: no input files
compilation terminated.
configure:3493: $? = 1
configure:3482: cc -version >&5
cc: error: unrecognized command-line option '-version'
cc: fatal error: no input files
compilation terminated.
configure:3493: $? = 1
configure:3513: checking whether the C compiler works
configure:3535: cc  -DV8_COMPRESS_POINTERS -lstdc++ conftest.c  >&5
configure:3539: $? = 0
configure:3589: result: yes
configure:3592: checking for C compiler default output file name
configure:3594: result: a.out
configure:3600: checking for suffix of executables
configure:3607: cc -o conftest  -DV8_COMPRESS_POINTERS -lstdc++ conftest.c  >&5
configure:3611: $? = 0
configure:3634: result: 
configure:3656: checking whether we are cross compiling
configure:3664: cc -o conftest  -DV8_COMPRESS_POINTERS -lstdc++ conftest.c  >&5
configure:3668: $? = 0
configure:3675: ./conftest
configure:3679: $? = 0
configure:3694: result: no
configure:3699: checking for suffix of object files
configure:3722: cc -c  -DV8_COMPRESS_POINTERS conftest.c >&5
configure:3726: $? = 0
configure:3748: result: o
configure:3752: checking whether the compiler supports GNU C
configure:3772: cc -c  -DV8_COMPRESS_POINTERS conftest.c >&5
configure:3772: $? = 0
configure:3782: result: yes
configure:3793: checking whether cc accepts -g
configure:3814: cc -c -g -DV8_COMPRESS_POINTERS conftest.c >&5
configure:3814: $? = 0
configure:3858: result: yes
configure:3878: checking for cc option to enable C11 features
configure:3893: cc  -c -g -O2 -DV8_COMPRESS_POINTERS conftest.c >&5
configure:3893: $? = 0
configure:3911: result: none needed
configure:4027: checking how to run the C preprocessor
configure:4053: cc -E -DV8_COMPRESS_POINTERS conftest.c
configure:4053: $? = 0
configure:4068: cc -E -DV8_COMPRESS_POINTERS conftest.c
conftest.c:9:10: fatal error: ac_nonexistent.h: No such file or directory
    9 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:4068: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:4095: result: cc -E
configure:4109: cc -E -DV8_COMPRESS_POINTERS conftest.c
configure:4109: $? = 0
configure:4124: cc -E -DV8_COMPRESS_POINTERS conftest.c
conftest.c:9:10: fatal error: ac_nonexistent.h: No such file or directory
    9 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:4124: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:4157: checking for icc
configure:4167: result: no
configure:4181: checking for suncc
configure:4191: result: no
configure:4209: checking for system library directory
configure:4225: result: lib
configure:4232: checking if compiler supports -Wl,-rpath,
configure:4252: cc -o conftest -g -O2 -DV8_COMPRESS_POINTERS -lstdc++ conftest.c -Wl,-rpath,/usr/lib  >&5
configure:4252: $? = 0
configure:4263: result: yes
configure:4318: checking build system type
configure:4333: result: x86_64-pc-linux-gnu
configure:4353: checking host system type
configure:4367: result: x86_64-pc-linux-gnu
configure:4387: checking target system type
configure:4401: result: x86_64-pc-linux-gnu
configure:4505: checking for PHP prefix
configure:4507: result: /usr
configure:4509: checking for PHP includes
configure:4511: result: -I/usr/include/php/20210902 -I/usr/include/php/20210902/main -I/usr/include/php/20210902/TSRM -I/usr/include/php/20210902/Zend -I/usr/include/php/20210902/ext -I/usr/include/php/20210902/ext/date/lib
configure:4513: checking for PHP extension directory
configure:4515: result: /usr/lib/php/20210902
configure:4517: checking for PHP installed headers prefix
configure:4519: result: /usr/include/php/20210902
configure:4522: checking if debug is enabled
configure:4549: result: no
configure:4552: checking if zts is enabled
configure:4579: result: no
configure:4647: checking for gawk
configure:4683: result: no
configure:4647: checking for nawk
configure:4669: found /usr/bin/nawk
configure:4680: result: nawk
configure:4703: checking if nawk is broken
configure:4710: result: no
configure:4723: checking for V8 Javascript Engine
configure:4764: result: yes, shared
configure:5008: checking for g++
configure:5029: found /usr/bin/g++
configure:5040: result: g++
configure:5067: checking for C++ compiler version
configure:5076: g++ --version >&5
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:5087: $? = 0
configure:5076: g++ -v >&5
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04) 
... rest of stderr output deleted ...
configure:5087: $? = 0
configure:5076: g++ -V >&5
g++: error: unrecognized command-line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:5087: $? = 1
configure:5076: g++ -qversion >&5
g++: error: unrecognized command-line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
compilation terminated.
configure:5087: $? = 1
configure:5091: checking whether the compiler supports GNU C++
configure:5111: g++ -c  -DV8_COMPRESS_POINTERS conftest.cpp >&5
configure:5111: $? = 0
configure:5121: result: yes
configure:5132: checking whether g++ accepts -g
configure:5153: g++ -c -g -DV8_COMPRESS_POINTERS conftest.cpp >&5
configure:5153: $? = 0
configure:5197: result: yes
configure:5217: checking for g++ option to enable C++11 features
configure:5232: g++  -c -g -O2 -DV8_COMPRESS_POINTERS conftest.cpp >&5
conftest.cpp: In function 'int main(int, char**)':
conftest.cpp:176:25: warning: empty parentheses were disambiguated as a function declaration [-Wvexing-parse]
  176 |   cxx11test::delegate d2();
      |                         ^~
conftest.cpp:176:25: note: remove parentheses to default-initialize a variable
  176 |   cxx11test::delegate d2();
      |                         ^~
      |                         --
conftest.cpp:176:25: note: or replace parentheses with braces to value-initialize a variable
configure:5232: $? = 0
configure:5250: result: none needed
configure:5319: checking how to run the C++ preprocessor
configure:5341: g++ -E -DV8_COMPRESS_POINTERS conftest.cpp
configure:5341: $? = 0
configure:5356: g++ -E -DV8_COMPRESS_POINTERS conftest.cpp
conftest.cpp:10:10: fatal error: ac_nonexistent.h: No such file or directory
   10 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:5356: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PHP_V8_EXEC_PATH "/opt/v8/lib/libv8.so"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:5383: result: g++ -E
configure:5397: g++ -E -DV8_COMPRESS_POINTERS conftest.cpp
configure:5397: $? = 0
configure:5412: g++ -E -DV8_COMPRESS_POINTERS conftest.cpp
conftest.cpp:10:10: fatal error: ac_nonexistent.h: No such file or directory
   10 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:5412: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PHP_V8_EXEC_PATH "/opt/v8/lib/libv8.so"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:5458: checking for C standard version
configure:5485: g++ -o conftest -g -O2 -std=c++14 -lstdc++ -Wl,--rpath=/opt/v8/lib conftest.cpp -lstdc++  >&5
configure:5485: $? = 0
configure:5485: ./conftest
configure:5485: $? = 0
configure:5504: result: c++14
configure:5507: checking how to allow c++14 narrowing
configure:5538: g++ -o conftest -std=c++14 -DV8_COMPRESS_POINTERS -lstdc++ -Wl,--rpath=/opt/v8/lib conftest.cpp -lstdc++  >&5
conftest.cpp: In function 'int main()':
conftest.cpp:11:45: error: narrowing conversion of '-1' from 'int' to 'unsigned int' [-Wnarrowing]
   11 |         struct { unsigned int x; } foo = {-1};
      |                                             ^
configure:5538: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PHP_V8_EXEC_PATH "/opt/v8/lib/libv8.so"
| /* end confdefs.h.  */
| int main() {
|         struct { unsigned int x; } foo = {-1};
|         (void) foo;
|         return 0;
|     }
configure:5559: g++ -o conftest -Wno-c++14-narrowing -std=c++14 -DV8_COMPRESS_POINTERS -lstdc++ -Wl,--rpath=/opt/v8/lib conftest.cpp -lstdc++  >&5
conftest.cpp: In function 'int main()':
conftest.cpp:11:49: error: narrowing conversion of '-1' from 'int' to 'unsigned int' [-Wnarrowing]
   11 |             struct { unsigned int x; } foo = {-1};
      |                                                 ^
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-c++14-narrowing' may have been intended to silence earlier diagnostics
configure:5559: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PHP_V8_EXEC_PATH "/opt/v8/lib/libv8.so"
| /* end confdefs.h.  */
| int main() {
|             struct { unsigned int x; } foo = {-1};
|             (void) foo;
|             return 0;
|         }
configure:5580: g++ -o conftest -Wno-narrowing -std=c++14 -DV8_COMPRESS_POINTERS -lstdc++ -Wl,--rpath=/opt/v8/lib conftest.cpp -lstdc++  >&5
configure:5580: $? = 0
configure:5580: ./conftest
configure:5580: $? = 0
configure:5613: result: -Wno-narrowing
configure:5631: checking for libv8_libplatform
configure:5651: g++ -o conftest -g -O2 -DV8_COMPRESS_POINTERS -I/opt/v8/include -std=c++14 -lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 >&5
configure:5651: $? = 0
configure:5654: result: found
configure:5703: checking for V8 version
configure:5733: g++ -o conftest -g -O2 -DV8_COMPRESS_POINTERS -I/opt/v8/include -std=c++14 -lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib conftest.cpp -lstdc++   -lv8_libplatform -Wl,-rpath,/opt/v8/lib -L/opt/v8/lib -lv8  >&5
In file included from /opt/v8/include/v8-object.h:9,
                 from /opt/v8/include/v8-array-buffer.h:13,
                 from /opt/v8/include/v8.h:24,
                 from conftest.cpp:10:
/opt/v8/include/v8-maybe.h:106:45: error: 'is_lvalue_reference_v' is not a member of 'std'; did you mean 'is_lvalue_reference'?
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                             ^~~~~~~~~~~~~~~~~~~~~
      |                                             is_lvalue_reference
/opt/v8/include/v8-maybe.h:106:67: error: template argument 1 is invalid
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                   ^
/opt/v8/include/v8-maybe.h:106:71: error: expected unqualified-id before '>' token
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                       ^
/opt/v8/include/v8-maybe.h:123:43: error: 'is_lvalue_reference_v' is not a member of 'std'; did you mean 'is_lvalue_reference'?
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                           ^~~~~~~~~~~~~~~~~~~~~
      |                                           is_lvalue_reference
/opt/v8/include/v8-maybe.h:123:65: error: template argument 1 is invalid
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                 ^
/opt/v8/include/v8-maybe.h:123:70: error: expected unqualified-id before '=' token
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                      ^
configure:5733: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PHP_V8_EXEC_PATH "/opt/v8/lib/libv8.so"
| /* end confdefs.h.  */
| #include <v8.h>
| #include <iostream>
| #include <fstream>
| using namespace std;
| 
| int main ()
| {
| 	ofstream testfile ("conftestval");
| 	if (testfile.is_open()) {
| 		testfile << v8::V8::GetVersion();
| 		testfile << "\n";
| 		testfile.close();
| 		return 0;
| 	}
| 	return 1;
| }
configure:5745: result: NONE
configure:5764: error: could not determine libv8 version

## ---------------- ##

ac_cv_build=x86_64-pc-linux-gnu
ac_cv_c_compiler_gnu=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value=-DV8_COMPRESS_POINTERS
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value=-lstdc++
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-pc-linux-gnu
ac_cv_objext=o
ac_cv_path_EGREP='/usr/bin/grep -E'
ac_cv_path_GREP=/usr/bin/grep
ac_cv_path_SED=/usr/bin/sed
ac_cv_path_ac_pt_PKG_CONFIG=/usr/bin/pkg-config
ac_cv_prog_AWK=nawk
ac_cv_prog_CPP='cc -E'
ac_cv_prog_CXXCPP='g++ -E'
ac_cv_prog_ac_ct_CC=cc
ac_cv_prog_ac_ct_CXX=g++
ac_cv_prog_cc_c11=
ac_cv_prog_cc_g=yes
ac_cv_prog_cc_stdc=
ac_cv_prog_cxx_11=no
ac_cv_prog_cxx_cxx11=
ac_cv_prog_cxx_g=yes
ac_cv_prog_cxx_stdcxx=
ac_cv_target=x86_64-pc-linux-gnu
ac_cv_v8_cstd=c++14
ac_cv_v8_narrowing=-Wno-narrowing
ac_cv_v8_version=NONE
php_cv_cc_rpath=yes

## ----------------- ##

AR=''
AWK='nawk'
BUILD_CC=''
CC='cc'
CFLAGS='-g -O2'
CONFIGURE_COMMAND=' '\''./configure'\''  '\''--with-v8js=/opt/v8'\'''
CONFIGURE_OPTIONS=' '\''--with-v8js=/opt/v8'\'''
CPP='cc -E'
CPPFLAGS='-DV8_COMPRESS_POINTERS -I/opt/v8/include -std=c++14'
CXX='g++'
CXXCPP='g++ -E'
CXXFLAGS='-g -O2'
DEFS=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/usr/bin/grep -E'
EXEEXT=''
FGREP=''
GREP='/usr/bin/grep'
LD=''
LDFLAGS='-lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib'
LIBOBJS=''
LIBS='-lstdc++   -lv8_libplatform -Wl,-rpath,/opt/v8/lib -L/opt/v8/lib -lv8 '
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MANIFEST_TOOL=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT='o'
OTOOL64=''
OTOOL=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
PKG_CONFIG='/usr/bin/pkg-config'
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
RANLIB=''
SED='/usr/bin/sed'
SHELL='/bin/bash'
SHLIB_DL_SUFFIX_NAME='so'
SHLIB_SUFFIX_NAME='so'
STRIP=''
ac_ct_AR=''
ac_ct_CC='cc'
ac_ct_CXX='g++'
ac_ct_DUMPBIN=''
bindir='${exec_prefix}/bin'
build='x86_64-pc-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-pc-linux-gnu'
host_alias='x86_64-pc-linux-gnu'
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='x86_64-pc-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='pc'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PHP_V8_EXEC_PATH "/opt/v8/lib/libv8.so"

configure: exit 1`

**Comment by stesie** [comment]
> configure:5733: g++ -o conftest -g -O2 -DV8_COMPRESS_POINTERS -I/opt/v8/include -std=c++14 -lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib conftest.cpp -lstdc++ -lv8_libplatform -Wl,-rpath,/opt/v8/lib -L/opt/v8/lib -lv8

`config.log` shows that it's still using c++14 compiler standard.  You need to re-run `phpize` after modifying `config.m4` file

**Comment by rzarectah88** [comment]
@stesie Thanks for the response, I was able to get past the error by re-running phpize like you suggested, however, now getting this error during `make`

`/tmp/v8js/v8js_main.cc:165:11: error: no member named 'ShutdownPlatform' in 'v8::V8'`
`                v8::V8::ShutdownPlatform();`

**Comment by rzarectah88** [comment]
~So I was able to install it using version `10.1.124.12` on my ubuntu 22 laptop but still no luck on mac os or vps ubuntu. Can I just use the `v8js.so` from my laptop on my mac or another ubuntu 22 server?~

I was able to compile for mac and ubuntu laptop/vps using `v8` version `9.6.180.29` and `php8.0` with `98.2%` tests passed
