### ISSUE TITLE
Broken build on PHP 8.0.x

### ISSUE THREAD

**Issue by marekskopal** [phpv8/v8js#502]
Hi,

After changes from this pull request https://github.com/phpv8/v8js/pull/498 build on PHP 8.0.x is broken. 

If I revert those changes, build works fine.

On 8.1.x its fine too.

I suppose that `zend_is_graceful_exit` is not present in 8.0

**Comment by marekskopal** [comment]
I created a pull request that should fix it https://github.com/phpv8/v8js/pull/503

**Comment by stesie** [comment]
PR's merged.  Thanks for pointing this out 👍
