### ISSUE TITLE
Is there an official installation tutorial for the v8js extension?

### ISSUE THREAD

**Issue by mlwlkj** [phpv8/v8js#530]
The functionality of this extension is very powerful, but it is too difficult to install, and there are hardly any useful installation tutorials available online. Does the official have their own installation tutorial documentation?
I can't wait to use this library, but I always can't install it. Could the author provide an effective installation tutorial? Thank you very much.

**Comment by osbre** [comment]
I suppose you'd install it like any other pecl extension

**Comment by stesie** [comment]
you've seen the README.Linux.md file? It has detailed installation instructions after all ...

-> https://github.com/phpv8/v8js/blob/php8/README.Linux.md
